// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clientmocks

import (
	"context"
	"sync"
)

// ThunderProberMock is a mock implementation of thundersvc.Prober.
//
//	func TestSomethingThatUsesProber(t *testing.T) {
//
//		// make and configure a mocked thundersvc.Prober
//		mockedProber := &ThunderProberMock{
//			ProbeFunc: func(ctx context.Context, org string, env string) bool {
//				panic("mock out the Probe method")
//			},
//		}
//
//		// use mockedProber in code that requires thundersvc.Prober
//		// and then make assertions.
//
//	}
type ThunderProberMock struct {
	// ProbeFunc mocks the Probe method.
	ProbeFunc func(ctx context.Context, org string, env string) bool

	// calls tracks calls to the methods.
	calls struct {
		// Probe holds details about calls to the Probe method.
		Probe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Org is the org argument value.
			Org string
			// Env is the env argument value.
			Env string
		}
	}
	lockProbe sync.RWMutex
}

// Probe calls ProbeFunc.
func (mock *ThunderProberMock) Probe(ctx context.Context, org string, env string) bool {
	if mock.ProbeFunc == nil {
		panic("ThunderProberMock.ProbeFunc: method is nil but Prober.Probe was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Org string
		Env string
	}{
		Ctx: ctx,
		Org: org,
		Env: env,
	}
	mock.lockProbe.Lock()
	mock.calls.Probe = append(mock.calls.Probe, callInfo)
	mock.lockProbe.Unlock()
	return mock.ProbeFunc(ctx, org, env)
}

// ProbeCalls gets all the calls that were made to Probe.
// Check the length with:
//
//	len(mockedProber.ProbeCalls())
func (mock *ThunderProberMock) ProbeCalls() []struct {
	Ctx context.Context
	Org string
	Env string
} {
	var calls []struct {
		Ctx context.Context
		Org string
		Env string
	}
	mock.lockProbe.RLock()
	calls = mock.calls.Probe
	mock.lockProbe.RUnlock()
	return calls
}
