/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GitHubAppSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitHubAppSource{}

// GitHubAppSource Optional GitHub App source binding for cloud deployments. The control plane consumes this metadata, persists it through the deployment-provided repository source provider, and never forwards it to OpenChoreo. When omitted, public-repository and PAT-backed behavior is unchanged.
type GitHubAppSource struct {
	// GitHub App installation that grants access to the repository
	InstallationId int64 `json:"installationId"`
	// GitHub repository owner or organization
	Owner string `json:"owner"`
	// GitHub repository name without the owner prefix
	Repo string `json:"repo"`
	// Branch to build; defaults to provisioning.repository.branch
	Branch *string `json:"branch,omitempty"`
	// Source directory; defaults to provisioning.repository.appPath
	AppPath *string `json:"appPath,omitempty"`
	// Repository clone URL; defaults to provisioning.repository.url
	RepositoryUrl *string `json:"repositoryUrl,omitempty"`
}

// NewGitHubAppSource instantiates a new GitHubAppSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitHubAppSource(installationId int64, owner string, repo string) *GitHubAppSource {
	this := GitHubAppSource{}
	this.InstallationId = installationId
	this.Owner = owner
	this.Repo = repo
	return &this
}

// NewGitHubAppSourceWithDefaults instantiates a new GitHubAppSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitHubAppSourceWithDefaults() *GitHubAppSource {
	this := GitHubAppSource{}
	return &this
}

// GetInstallationId returns the InstallationId field value
func (o *GitHubAppSource) GetInstallationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.InstallationId
}

// GetInstallationIdOk returns a tuple with the InstallationId field value
// and a boolean to check if the value has been set.
func (o *GitHubAppSource) GetInstallationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstallationId, true
}

// SetInstallationId sets field value
func (o *GitHubAppSource) SetInstallationId(v int64) {
	o.InstallationId = v
}

// GetOwner returns the Owner field value
func (o *GitHubAppSource) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *GitHubAppSource) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *GitHubAppSource) SetOwner(v string) {
	o.Owner = v
}

// GetRepo returns the Repo field value
func (o *GitHubAppSource) GetRepo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Repo
}

// GetRepoOk returns a tuple with the Repo field value
// and a boolean to check if the value has been set.
func (o *GitHubAppSource) GetRepoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Repo, true
}

// SetRepo sets field value
func (o *GitHubAppSource) SetRepo(v string) {
	o.Repo = v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *GitHubAppSource) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitHubAppSource) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *GitHubAppSource) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *GitHubAppSource) SetBranch(v string) {
	o.Branch = &v
}

// GetAppPath returns the AppPath field value if set, zero value otherwise.
func (o *GitHubAppSource) GetAppPath() string {
	if o == nil || IsNil(o.AppPath) {
		var ret string
		return ret
	}
	return *o.AppPath
}

// GetAppPathOk returns a tuple with the AppPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitHubAppSource) GetAppPathOk() (*string, bool) {
	if o == nil || IsNil(o.AppPath) {
		return nil, false
	}
	return o.AppPath, true
}

// HasAppPath returns a boolean if a field has been set.
func (o *GitHubAppSource) HasAppPath() bool {
	if o != nil && !IsNil(o.AppPath) {
		return true
	}

	return false
}

// SetAppPath gets a reference to the given string and assigns it to the AppPath field.
func (o *GitHubAppSource) SetAppPath(v string) {
	o.AppPath = &v
}

// GetRepositoryUrl returns the RepositoryUrl field value if set, zero value otherwise.
func (o *GitHubAppSource) GetRepositoryUrl() string {
	if o == nil || IsNil(o.RepositoryUrl) {
		var ret string
		return ret
	}
	return *o.RepositoryUrl
}

// GetRepositoryUrlOk returns a tuple with the RepositoryUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitHubAppSource) GetRepositoryUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RepositoryUrl) {
		return nil, false
	}
	return o.RepositoryUrl, true
}

// HasRepositoryUrl returns a boolean if a field has been set.
func (o *GitHubAppSource) HasRepositoryUrl() bool {
	if o != nil && !IsNil(o.RepositoryUrl) {
		return true
	}

	return false
}

// SetRepositoryUrl gets a reference to the given string and assigns it to the RepositoryUrl field.
func (o *GitHubAppSource) SetRepositoryUrl(v string) {
	o.RepositoryUrl = &v
}

func (o GitHubAppSource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitHubAppSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["installationId"] = o.InstallationId
	toSerialize["owner"] = o.Owner
	toSerialize["repo"] = o.Repo
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.AppPath) {
		toSerialize["appPath"] = o.AppPath
	}
	if !IsNil(o.RepositoryUrl) {
		toSerialize["repositoryUrl"] = o.RepositoryUrl
	}
	return toSerialize, nil
}

type NullableGitHubAppSource struct {
	value *GitHubAppSource
	isSet bool
}

func (v NullableGitHubAppSource) Get() *GitHubAppSource {
	return v.value
}

func (v *NullableGitHubAppSource) Set(val *GitHubAppSource) {
	v.value = val
	v.isSet = true
}

func (v NullableGitHubAppSource) IsSet() bool {
	return v.isSet
}

func (v *NullableGitHubAppSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitHubAppSource(val *GitHubAppSource) *NullableGitHubAppSource {
	return &NullableGitHubAppSource{value: val, isSet: true}
}

func (v NullableGitHubAppSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitHubAppSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
