/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ConfigurationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationResponse{}

// ConfigurationResponse struct for ConfigurationResponse
type ConfigurationResponse struct {
	// Name of the project
	ProjectName string `json:"projectName"`
	// Name of the agent
	AgentName string `json:"agentName"`
	// Environment name
	Environment    string                              `json:"environment"`
	Configurations ConfigurationResponseConfigurations `json:"configurations"`
}

// NewConfigurationResponse instantiates a new ConfigurationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationResponse(projectName string, agentName string, environment string, configurations ConfigurationResponseConfigurations) *ConfigurationResponse {
	this := ConfigurationResponse{}
	this.ProjectName = projectName
	this.AgentName = agentName
	this.Environment = environment
	this.Configurations = configurations
	return &this
}

// NewConfigurationResponseWithDefaults instantiates a new ConfigurationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationResponseWithDefaults() *ConfigurationResponse {
	this := ConfigurationResponse{}
	return &this
}

// GetProjectName returns the ProjectName field value
func (o *ConfigurationResponse) GetProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *ConfigurationResponse) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectName, true
}

// SetProjectName sets field value
func (o *ConfigurationResponse) SetProjectName(v string) {
	o.ProjectName = v
}

// GetAgentName returns the AgentName field value
func (o *ConfigurationResponse) GetAgentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value
// and a boolean to check if the value has been set.
func (o *ConfigurationResponse) GetAgentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentName, true
}

// SetAgentName sets field value
func (o *ConfigurationResponse) SetAgentName(v string) {
	o.AgentName = v
}

// GetEnvironment returns the Environment field value
func (o *ConfigurationResponse) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *ConfigurationResponse) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *ConfigurationResponse) SetEnvironment(v string) {
	o.Environment = v
}

// GetConfigurations returns the Configurations field value
func (o *ConfigurationResponse) GetConfigurations() ConfigurationResponseConfigurations {
	if o == nil {
		var ret ConfigurationResponseConfigurations
		return ret
	}

	return o.Configurations
}

// GetConfigurationsOk returns a tuple with the Configurations field value
// and a boolean to check if the value has been set.
func (o *ConfigurationResponse) GetConfigurationsOk() (*ConfigurationResponseConfigurations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configurations, true
}

// SetConfigurations sets field value
func (o *ConfigurationResponse) SetConfigurations(v ConfigurationResponseConfigurations) {
	o.Configurations = v
}

func (o ConfigurationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectName"] = o.ProjectName
	toSerialize["agentName"] = o.AgentName
	toSerialize["environment"] = o.Environment
	toSerialize["configurations"] = o.Configurations
	return toSerialize, nil
}

type NullableConfigurationResponse struct {
	value *ConfigurationResponse
	isSet bool
}

func (v NullableConfigurationResponse) Get() *ConfigurationResponse {
	return v.value
}

func (v *NullableConfigurationResponse) Set(val *ConfigurationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationResponse(val *ConfigurationResponse) *NullableConfigurationResponse {
	return &NullableConfigurationResponse{value: val, isSet: true}
}

func (v NullableConfigurationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
