/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the FileMount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileMount{}

// FileMount struct for FileMount
type FileMount struct {
	// File name/key identifier
	Key string `json:"key"`
	// Mount path in container (absolute path, no '..' segments)
	MountPath string `json:"mountPath"`
	// File content (plain text or secret value for input; omitted for secrets in responses)
	Value *string `json:"value,omitempty"`
	// If true, value is stored in KV and synced via ExternalSecret
	IsSensitive *bool `json:"isSensitive,omitempty"`
	// Reference to existing secret.
	SecretRef *string `json:"secretRef,omitempty"`
}

// NewFileMount instantiates a new FileMount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileMount(key string, mountPath string) *FileMount {
	this := FileMount{}
	this.Key = key
	this.MountPath = mountPath
	var isSensitive bool = false
	this.IsSensitive = &isSensitive
	return &this
}

// NewFileMountWithDefaults instantiates a new FileMount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileMountWithDefaults() *FileMount {
	this := FileMount{}
	var isSensitive bool = false
	this.IsSensitive = &isSensitive
	return &this
}

// GetKey returns the Key field value
func (o *FileMount) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *FileMount) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *FileMount) SetKey(v string) {
	o.Key = v
}

// GetMountPath returns the MountPath field value
func (o *FileMount) GetMountPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MountPath
}

// GetMountPathOk returns a tuple with the MountPath field value
// and a boolean to check if the value has been set.
func (o *FileMount) GetMountPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MountPath, true
}

// SetMountPath sets field value
func (o *FileMount) SetMountPath(v string) {
	o.MountPath = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *FileMount) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileMount) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *FileMount) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *FileMount) SetValue(v string) {
	o.Value = &v
}

// GetIsSensitive returns the IsSensitive field value if set, zero value otherwise.
func (o *FileMount) GetIsSensitive() bool {
	if o == nil || IsNil(o.IsSensitive) {
		var ret bool
		return ret
	}
	return *o.IsSensitive
}

// GetIsSensitiveOk returns a tuple with the IsSensitive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileMount) GetIsSensitiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSensitive) {
		return nil, false
	}
	return o.IsSensitive, true
}

// HasIsSensitive returns a boolean if a field has been set.
func (o *FileMount) HasIsSensitive() bool {
	if o != nil && !IsNil(o.IsSensitive) {
		return true
	}

	return false
}

// SetIsSensitive gets a reference to the given bool and assigns it to the IsSensitive field.
func (o *FileMount) SetIsSensitive(v bool) {
	o.IsSensitive = &v
}

// GetSecretRef returns the SecretRef field value if set, zero value otherwise.
func (o *FileMount) GetSecretRef() string {
	if o == nil || IsNil(o.SecretRef) {
		var ret string
		return ret
	}
	return *o.SecretRef
}

// GetSecretRefOk returns a tuple with the SecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileMount) GetSecretRefOk() (*string, bool) {
	if o == nil || IsNil(o.SecretRef) {
		return nil, false
	}
	return o.SecretRef, true
}

// HasSecretRef returns a boolean if a field has been set.
func (o *FileMount) HasSecretRef() bool {
	if o != nil && !IsNil(o.SecretRef) {
		return true
	}

	return false
}

// SetSecretRef gets a reference to the given string and assigns it to the SecretRef field.
func (o *FileMount) SetSecretRef(v string) {
	o.SecretRef = &v
}

func (o FileMount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileMount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["mountPath"] = o.MountPath
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.IsSensitive) {
		toSerialize["isSensitive"] = o.IsSensitive
	}
	if !IsNil(o.SecretRef) {
		toSerialize["secretRef"] = o.SecretRef
	}
	return toSerialize, nil
}

type NullableFileMount struct {
	value *FileMount
	isSet bool
}

func (v NullableFileMount) Get() *FileMount {
	return v.value
}

func (v *NullableFileMount) Set(val *FileMount) {
	v.value = val
	v.isSet = true
}

func (v NullableFileMount) IsSet() bool {
	return v.isSet
}

func (v *NullableFileMount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileMount(val *FileMount) *NullableFileMount {
	return &NullableFileMount{value: val, isSet: true}
}

func (v NullableFileMount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileMount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
