/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ModelConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelConfigRequest{}

// ModelConfigRequest struct for ModelConfigRequest
type ModelConfigRequest struct {
	// Handle of an already-configured LLM provider. Applied to the component's initial (lowest) environment.
	ProviderName  string                    `json:"providerName"`
	Configuration *EnvProviderConfiguration `json:"configuration,omitempty"`
	// Optional custom environment variable names exposed to the agent
	EnvironmentVariables []EnvironmentVariableConfig `json:"environmentVariables,omitempty"`
}

// NewModelConfigRequest instantiates a new ModelConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelConfigRequest(providerName string) *ModelConfigRequest {
	this := ModelConfigRequest{}
	this.ProviderName = providerName
	return &this
}

// NewModelConfigRequestWithDefaults instantiates a new ModelConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelConfigRequestWithDefaults() *ModelConfigRequest {
	this := ModelConfigRequest{}
	return &this
}

// GetProviderName returns the ProviderName field value
func (o *ModelConfigRequest) GetProviderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderName
}

// GetProviderNameOk returns a tuple with the ProviderName field value
// and a boolean to check if the value has been set.
func (o *ModelConfigRequest) GetProviderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderName, true
}

// SetProviderName sets field value
func (o *ModelConfigRequest) SetProviderName(v string) {
	o.ProviderName = v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *ModelConfigRequest) GetConfiguration() EnvProviderConfiguration {
	if o == nil || IsNil(o.Configuration) {
		var ret EnvProviderConfiguration
		return ret
	}
	return *o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelConfigRequest) GetConfigurationOk() (*EnvProviderConfiguration, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *ModelConfigRequest) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given EnvProviderConfiguration and assigns it to the Configuration field.
func (o *ModelConfigRequest) SetConfiguration(v EnvProviderConfiguration) {
	o.Configuration = &v
}

// GetEnvironmentVariables returns the EnvironmentVariables field value if set, zero value otherwise.
func (o *ModelConfigRequest) GetEnvironmentVariables() []EnvironmentVariableConfig {
	if o == nil || IsNil(o.EnvironmentVariables) {
		var ret []EnvironmentVariableConfig
		return ret
	}
	return o.EnvironmentVariables
}

// GetEnvironmentVariablesOk returns a tuple with the EnvironmentVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelConfigRequest) GetEnvironmentVariablesOk() ([]EnvironmentVariableConfig, bool) {
	if o == nil || IsNil(o.EnvironmentVariables) {
		return nil, false
	}
	return o.EnvironmentVariables, true
}

// HasEnvironmentVariables returns a boolean if a field has been set.
func (o *ModelConfigRequest) HasEnvironmentVariables() bool {
	if o != nil && !IsNil(o.EnvironmentVariables) {
		return true
	}

	return false
}

// SetEnvironmentVariables gets a reference to the given []EnvironmentVariableConfig and assigns it to the EnvironmentVariables field.
func (o *ModelConfigRequest) SetEnvironmentVariables(v []EnvironmentVariableConfig) {
	o.EnvironmentVariables = v
}

func (o ModelConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["providerName"] = o.ProviderName
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	if !IsNil(o.EnvironmentVariables) {
		toSerialize["environmentVariables"] = o.EnvironmentVariables
	}
	return toSerialize, nil
}

type NullableModelConfigRequest struct {
	value *ModelConfigRequest
	isSet bool
}

func (v NullableModelConfigRequest) Get() *ModelConfigRequest {
	return v.value
}

func (v *NullableModelConfigRequest) Set(val *ModelConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelConfigRequest(val *ModelConfigRequest) *NullableModelConfigRequest {
	return &NullableModelConfigRequest{value: val, isSet: true}
}

func (v NullableModelConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
