/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpdateAgentDeploySettingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAgentDeploySettingsRequest{}

// UpdateAgentDeploySettingsRequest struct for UpdateAgentDeploySettingsRequest
type UpdateAgentDeploySettingsRequest struct {
	// Name of the environment whose deploy settings to update.
	EnvironmentName string `json:"environmentName"`
	// Enable auto instrumentation for observability in this environment. Omit to keep the current value.
	EnableAutoInstrumentation *bool `json:"enableAutoInstrumentation,omitempty"`
	// Enable API key security for the agent endpoint in this environment. Omit to keep the current value.
	EnableApiKeySecurity *bool       `json:"enableApiKeySecurity,omitempty"`
	CorsConfig           *CORSConfig `json:"corsConfig,omitempty"`
	// Enable OAuth security for the agent endpoint in this environment. Mutually exclusive with enableApiKeySecurity. Omit to keep the current value.
	EnableOAuthSecurity *bool        `json:"enableOAuthSecurity,omitempty"`
	OauthConfig         *OAuthConfig `json:"oauthConfig,omitempty"`
}

// NewUpdateAgentDeploySettingsRequest instantiates a new UpdateAgentDeploySettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAgentDeploySettingsRequest(environmentName string) *UpdateAgentDeploySettingsRequest {
	this := UpdateAgentDeploySettingsRequest{}
	this.EnvironmentName = environmentName
	return &this
}

// NewUpdateAgentDeploySettingsRequestWithDefaults instantiates a new UpdateAgentDeploySettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAgentDeploySettingsRequestWithDefaults() *UpdateAgentDeploySettingsRequest {
	this := UpdateAgentDeploySettingsRequest{}
	return &this
}

// GetEnvironmentName returns the EnvironmentName field value
func (o *UpdateAgentDeploySettingsRequest) GetEnvironmentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentName
}

// GetEnvironmentNameOk returns a tuple with the EnvironmentName field value
// and a boolean to check if the value has been set.
func (o *UpdateAgentDeploySettingsRequest) GetEnvironmentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentName, true
}

// SetEnvironmentName sets field value
func (o *UpdateAgentDeploySettingsRequest) SetEnvironmentName(v string) {
	o.EnvironmentName = v
}

// GetEnableAutoInstrumentation returns the EnableAutoInstrumentation field value if set, zero value otherwise.
func (o *UpdateAgentDeploySettingsRequest) GetEnableAutoInstrumentation() bool {
	if o == nil || IsNil(o.EnableAutoInstrumentation) {
		var ret bool
		return ret
	}
	return *o.EnableAutoInstrumentation
}

// GetEnableAutoInstrumentationOk returns a tuple with the EnableAutoInstrumentation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAgentDeploySettingsRequest) GetEnableAutoInstrumentationOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableAutoInstrumentation) {
		return nil, false
	}
	return o.EnableAutoInstrumentation, true
}

// HasEnableAutoInstrumentation returns a boolean if a field has been set.
func (o *UpdateAgentDeploySettingsRequest) HasEnableAutoInstrumentation() bool {
	if o != nil && !IsNil(o.EnableAutoInstrumentation) {
		return true
	}

	return false
}

// SetEnableAutoInstrumentation gets a reference to the given bool and assigns it to the EnableAutoInstrumentation field.
func (o *UpdateAgentDeploySettingsRequest) SetEnableAutoInstrumentation(v bool) {
	o.EnableAutoInstrumentation = &v
}

// GetEnableApiKeySecurity returns the EnableApiKeySecurity field value if set, zero value otherwise.
func (o *UpdateAgentDeploySettingsRequest) GetEnableApiKeySecurity() bool {
	if o == nil || IsNil(o.EnableApiKeySecurity) {
		var ret bool
		return ret
	}
	return *o.EnableApiKeySecurity
}

// GetEnableApiKeySecurityOk returns a tuple with the EnableApiKeySecurity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAgentDeploySettingsRequest) GetEnableApiKeySecurityOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableApiKeySecurity) {
		return nil, false
	}
	return o.EnableApiKeySecurity, true
}

// HasEnableApiKeySecurity returns a boolean if a field has been set.
func (o *UpdateAgentDeploySettingsRequest) HasEnableApiKeySecurity() bool {
	if o != nil && !IsNil(o.EnableApiKeySecurity) {
		return true
	}

	return false
}

// SetEnableApiKeySecurity gets a reference to the given bool and assigns it to the EnableApiKeySecurity field.
func (o *UpdateAgentDeploySettingsRequest) SetEnableApiKeySecurity(v bool) {
	o.EnableApiKeySecurity = &v
}

// GetCorsConfig returns the CorsConfig field value if set, zero value otherwise.
func (o *UpdateAgentDeploySettingsRequest) GetCorsConfig() CORSConfig {
	if o == nil || IsNil(o.CorsConfig) {
		var ret CORSConfig
		return ret
	}
	return *o.CorsConfig
}

// GetCorsConfigOk returns a tuple with the CorsConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAgentDeploySettingsRequest) GetCorsConfigOk() (*CORSConfig, bool) {
	if o == nil || IsNil(o.CorsConfig) {
		return nil, false
	}
	return o.CorsConfig, true
}

// HasCorsConfig returns a boolean if a field has been set.
func (o *UpdateAgentDeploySettingsRequest) HasCorsConfig() bool {
	if o != nil && !IsNil(o.CorsConfig) {
		return true
	}

	return false
}

// SetCorsConfig gets a reference to the given CORSConfig and assigns it to the CorsConfig field.
func (o *UpdateAgentDeploySettingsRequest) SetCorsConfig(v CORSConfig) {
	o.CorsConfig = &v
}

// GetEnableOAuthSecurity returns the EnableOAuthSecurity field value if set, zero value otherwise.
func (o *UpdateAgentDeploySettingsRequest) GetEnableOAuthSecurity() bool {
	if o == nil || IsNil(o.EnableOAuthSecurity) {
		var ret bool
		return ret
	}
	return *o.EnableOAuthSecurity
}

// GetEnableOAuthSecurityOk returns a tuple with the EnableOAuthSecurity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAgentDeploySettingsRequest) GetEnableOAuthSecurityOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableOAuthSecurity) {
		return nil, false
	}
	return o.EnableOAuthSecurity, true
}

// HasEnableOAuthSecurity returns a boolean if a field has been set.
func (o *UpdateAgentDeploySettingsRequest) HasEnableOAuthSecurity() bool {
	if o != nil && !IsNil(o.EnableOAuthSecurity) {
		return true
	}

	return false
}

// SetEnableOAuthSecurity gets a reference to the given bool and assigns it to the EnableOAuthSecurity field.
func (o *UpdateAgentDeploySettingsRequest) SetEnableOAuthSecurity(v bool) {
	o.EnableOAuthSecurity = &v
}

// GetOauthConfig returns the OauthConfig field value if set, zero value otherwise.
func (o *UpdateAgentDeploySettingsRequest) GetOauthConfig() OAuthConfig {
	if o == nil || IsNil(o.OauthConfig) {
		var ret OAuthConfig
		return ret
	}
	return *o.OauthConfig
}

// GetOauthConfigOk returns a tuple with the OauthConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAgentDeploySettingsRequest) GetOauthConfigOk() (*OAuthConfig, bool) {
	if o == nil || IsNil(o.OauthConfig) {
		return nil, false
	}
	return o.OauthConfig, true
}

// HasOauthConfig returns a boolean if a field has been set.
func (o *UpdateAgentDeploySettingsRequest) HasOauthConfig() bool {
	if o != nil && !IsNil(o.OauthConfig) {
		return true
	}

	return false
}

// SetOauthConfig gets a reference to the given OAuthConfig and assigns it to the OauthConfig field.
func (o *UpdateAgentDeploySettingsRequest) SetOauthConfig(v OAuthConfig) {
	o.OauthConfig = &v
}

func (o UpdateAgentDeploySettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAgentDeploySettingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environmentName"] = o.EnvironmentName
	if !IsNil(o.EnableAutoInstrumentation) {
		toSerialize["enableAutoInstrumentation"] = o.EnableAutoInstrumentation
	}
	if !IsNil(o.EnableApiKeySecurity) {
		toSerialize["enableApiKeySecurity"] = o.EnableApiKeySecurity
	}
	if !IsNil(o.CorsConfig) {
		toSerialize["corsConfig"] = o.CorsConfig
	}
	if !IsNil(o.EnableOAuthSecurity) {
		toSerialize["enableOAuthSecurity"] = o.EnableOAuthSecurity
	}
	if !IsNil(o.OauthConfig) {
		toSerialize["oauthConfig"] = o.OauthConfig
	}
	return toSerialize, nil
}

type NullableUpdateAgentDeploySettingsRequest struct {
	value *UpdateAgentDeploySettingsRequest
	isSet bool
}

func (v NullableUpdateAgentDeploySettingsRequest) Get() *UpdateAgentDeploySettingsRequest {
	return v.value
}

func (v *NullableUpdateAgentDeploySettingsRequest) Set(val *UpdateAgentDeploySettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAgentDeploySettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAgentDeploySettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAgentDeploySettingsRequest(val *UpdateAgentDeploySettingsRequest) *NullableUpdateAgentDeploySettingsRequest {
	return &NullableUpdateAgentDeploySettingsRequest{value: val, isSet: true}
}

func (v NullableUpdateAgentDeploySettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAgentDeploySettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
