/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpsertIdentityProviderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertIdentityProviderRequest{}

// UpsertIdentityProviderRequest Request body for creating or updating a gateway identity provider (name is taken from the path).
type UpsertIdentityProviderRequest struct {
	// Expected `iss` claim value for tokens validated by this identity provider.
	Issuer *string `json:"issuer,omitempty"`
	// Remote JWKS endpoint used to fetch signing keys.
	JwksUri *string `json:"jwksUri,omitempty"`
	// Skip TLS verification when fetching the JWKS endpoint.
	SkipTlsVerify *bool `json:"skipTlsVerify,omitempty"`
	// Optional human-readable description (mirror-only).
	Description *string `json:"description,omitempty"`
}

// NewUpsertIdentityProviderRequest instantiates a new UpsertIdentityProviderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertIdentityProviderRequest() *UpsertIdentityProviderRequest {
	this := UpsertIdentityProviderRequest{}
	var skipTlsVerify bool = false
	this.SkipTlsVerify = &skipTlsVerify
	return &this
}

// NewUpsertIdentityProviderRequestWithDefaults instantiates a new UpsertIdentityProviderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertIdentityProviderRequestWithDefaults() *UpsertIdentityProviderRequest {
	this := UpsertIdentityProviderRequest{}
	var skipTlsVerify bool = false
	this.SkipTlsVerify = &skipTlsVerify
	return &this
}

// GetIssuer returns the Issuer field value if set, zero value otherwise.
func (o *UpsertIdentityProviderRequest) GetIssuer() string {
	if o == nil || IsNil(o.Issuer) {
		var ret string
		return ret
	}
	return *o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertIdentityProviderRequest) GetIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.Issuer) {
		return nil, false
	}
	return o.Issuer, true
}

// HasIssuer returns a boolean if a field has been set.
func (o *UpsertIdentityProviderRequest) HasIssuer() bool {
	if o != nil && !IsNil(o.Issuer) {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given string and assigns it to the Issuer field.
func (o *UpsertIdentityProviderRequest) SetIssuer(v string) {
	o.Issuer = &v
}

// GetJwksUri returns the JwksUri field value if set, zero value otherwise.
func (o *UpsertIdentityProviderRequest) GetJwksUri() string {
	if o == nil || IsNil(o.JwksUri) {
		var ret string
		return ret
	}
	return *o.JwksUri
}

// GetJwksUriOk returns a tuple with the JwksUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertIdentityProviderRequest) GetJwksUriOk() (*string, bool) {
	if o == nil || IsNil(o.JwksUri) {
		return nil, false
	}
	return o.JwksUri, true
}

// HasJwksUri returns a boolean if a field has been set.
func (o *UpsertIdentityProviderRequest) HasJwksUri() bool {
	if o != nil && !IsNil(o.JwksUri) {
		return true
	}

	return false
}

// SetJwksUri gets a reference to the given string and assigns it to the JwksUri field.
func (o *UpsertIdentityProviderRequest) SetJwksUri(v string) {
	o.JwksUri = &v
}

// GetSkipTlsVerify returns the SkipTlsVerify field value if set, zero value otherwise.
func (o *UpsertIdentityProviderRequest) GetSkipTlsVerify() bool {
	if o == nil || IsNil(o.SkipTlsVerify) {
		var ret bool
		return ret
	}
	return *o.SkipTlsVerify
}

// GetSkipTlsVerifyOk returns a tuple with the SkipTlsVerify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertIdentityProviderRequest) GetSkipTlsVerifyOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipTlsVerify) {
		return nil, false
	}
	return o.SkipTlsVerify, true
}

// HasSkipTlsVerify returns a boolean if a field has been set.
func (o *UpsertIdentityProviderRequest) HasSkipTlsVerify() bool {
	if o != nil && !IsNil(o.SkipTlsVerify) {
		return true
	}

	return false
}

// SetSkipTlsVerify gets a reference to the given bool and assigns it to the SkipTlsVerify field.
func (o *UpsertIdentityProviderRequest) SetSkipTlsVerify(v bool) {
	o.SkipTlsVerify = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpsertIdentityProviderRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertIdentityProviderRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpsertIdentityProviderRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpsertIdentityProviderRequest) SetDescription(v string) {
	o.Description = &v
}

func (o UpsertIdentityProviderRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertIdentityProviderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Issuer) {
		toSerialize["issuer"] = o.Issuer
	}
	if !IsNil(o.JwksUri) {
		toSerialize["jwksUri"] = o.JwksUri
	}
	if !IsNil(o.SkipTlsVerify) {
		toSerialize["skipTlsVerify"] = o.SkipTlsVerify
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableUpsertIdentityProviderRequest struct {
	value *UpsertIdentityProviderRequest
	isSet bool
}

func (v NullableUpsertIdentityProviderRequest) Get() *UpsertIdentityProviderRequest {
	return v.value
}

func (v *NullableUpsertIdentityProviderRequest) Set(val *UpsertIdentityProviderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertIdentityProviderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertIdentityProviderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertIdentityProviderRequest(val *UpsertIdentityProviderRequest) *NullableUpsertIdentityProviderRequest {
	return &NullableUpsertIdentityProviderRequest{value: val, isSet: true}
}

func (v NullableUpsertIdentityProviderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertIdentityProviderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
