/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the IssueTestAPIKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IssueTestAPIKeyResponse{}

// IssueTestAPIKeyResponse struct for IssueTestAPIKeyResponse
type IssueTestAPIKeyResponse struct {
	Status  string  `json:"status"`
	Message *string `json:"message,omitempty"`
	// The fixed name \"console-test\".
	KeyId *string `json:"keyId,omitempty"`
	// The test API key value to send as the X-API-Key header.
	ApiKey *string `json:"apiKey,omitempty"`
	// Expiry timestamp (RFC3339); the console rotates the key before this elapses.
	ExpiresAt time.Time `json:"expiresAt"`
}

// NewIssueTestAPIKeyResponse instantiates a new IssueTestAPIKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssueTestAPIKeyResponse(status string, expiresAt time.Time) *IssueTestAPIKeyResponse {
	this := IssueTestAPIKeyResponse{}
	this.Status = status
	this.ExpiresAt = expiresAt
	return &this
}

// NewIssueTestAPIKeyResponseWithDefaults instantiates a new IssueTestAPIKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssueTestAPIKeyResponseWithDefaults() *IssueTestAPIKeyResponse {
	this := IssueTestAPIKeyResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *IssueTestAPIKeyResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *IssueTestAPIKeyResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *IssueTestAPIKeyResponse) SetStatus(v string) {
	o.Status = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *IssueTestAPIKeyResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueTestAPIKeyResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *IssueTestAPIKeyResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *IssueTestAPIKeyResponse) SetMessage(v string) {
	o.Message = &v
}

// GetKeyId returns the KeyId field value if set, zero value otherwise.
func (o *IssueTestAPIKeyResponse) GetKeyId() string {
	if o == nil || IsNil(o.KeyId) {
		var ret string
		return ret
	}
	return *o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueTestAPIKeyResponse) GetKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.KeyId) {
		return nil, false
	}
	return o.KeyId, true
}

// HasKeyId returns a boolean if a field has been set.
func (o *IssueTestAPIKeyResponse) HasKeyId() bool {
	if o != nil && !IsNil(o.KeyId) {
		return true
	}

	return false
}

// SetKeyId gets a reference to the given string and assigns it to the KeyId field.
func (o *IssueTestAPIKeyResponse) SetKeyId(v string) {
	o.KeyId = &v
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *IssueTestAPIKeyResponse) GetApiKey() string {
	if o == nil || IsNil(o.ApiKey) {
		var ret string
		return ret
	}
	return *o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueTestAPIKeyResponse) GetApiKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ApiKey) {
		return nil, false
	}
	return o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *IssueTestAPIKeyResponse) HasApiKey() bool {
	if o != nil && !IsNil(o.ApiKey) {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given string and assigns it to the ApiKey field.
func (o *IssueTestAPIKeyResponse) SetApiKey(v string) {
	o.ApiKey = &v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *IssueTestAPIKeyResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *IssueTestAPIKeyResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *IssueTestAPIKeyResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

func (o IssueTestAPIKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IssueTestAPIKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.KeyId) {
		toSerialize["keyId"] = o.KeyId
	}
	if !IsNil(o.ApiKey) {
		toSerialize["apiKey"] = o.ApiKey
	}
	toSerialize["expiresAt"] = o.ExpiresAt
	return toSerialize, nil
}

type NullableIssueTestAPIKeyResponse struct {
	value *IssueTestAPIKeyResponse
	isSet bool
}

func (v NullableIssueTestAPIKeyResponse) Get() *IssueTestAPIKeyResponse {
	return v.value
}

func (v *NullableIssueTestAPIKeyResponse) Set(val *IssueTestAPIKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIssueTestAPIKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIssueTestAPIKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssueTestAPIKeyResponse(val *IssueTestAPIKeyResponse) *NullableIssueTestAPIKeyResponse {
	return &NullableIssueTestAPIKeyResponse{value: val, isSet: true}
}

func (v NullableIssueTestAPIKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssueTestAPIKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
