/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ConfigurationResponseConfigurations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationResponseConfigurations{}

// ConfigurationResponseConfigurations Configuration data containing env vars and file mounts
type ConfigurationResponseConfigurations struct {
	// List of environment variable configurations
	Env []ConfigurationItem `json:"env"`
	// List of file mount configurations
	Files []FileMount `json:"files"`
}

// NewConfigurationResponseConfigurations instantiates a new ConfigurationResponseConfigurations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationResponseConfigurations(env []ConfigurationItem, files []FileMount) *ConfigurationResponseConfigurations {
	this := ConfigurationResponseConfigurations{}
	this.Env = env
	this.Files = files
	return &this
}

// NewConfigurationResponseConfigurationsWithDefaults instantiates a new ConfigurationResponseConfigurations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationResponseConfigurationsWithDefaults() *ConfigurationResponseConfigurations {
	this := ConfigurationResponseConfigurations{}
	return &this
}

// GetEnv returns the Env field value
func (o *ConfigurationResponseConfigurations) GetEnv() []ConfigurationItem {
	if o == nil {
		var ret []ConfigurationItem
		return ret
	}

	return o.Env
}

// GetEnvOk returns a tuple with the Env field value
// and a boolean to check if the value has been set.
func (o *ConfigurationResponseConfigurations) GetEnvOk() ([]ConfigurationItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Env, true
}

// SetEnv sets field value
func (o *ConfigurationResponseConfigurations) SetEnv(v []ConfigurationItem) {
	o.Env = v
}

// GetFiles returns the Files field value
func (o *ConfigurationResponseConfigurations) GetFiles() []FileMount {
	if o == nil {
		var ret []FileMount
		return ret
	}

	return o.Files
}

// GetFilesOk returns a tuple with the Files field value
// and a boolean to check if the value has been set.
func (o *ConfigurationResponseConfigurations) GetFilesOk() ([]FileMount, bool) {
	if o == nil {
		return nil, false
	}
	return o.Files, true
}

// SetFiles sets field value
func (o *ConfigurationResponseConfigurations) SetFiles(v []FileMount) {
	o.Files = v
}

func (o ConfigurationResponseConfigurations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationResponseConfigurations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["env"] = o.Env
	toSerialize["files"] = o.Files
	return toSerialize, nil
}

type NullableConfigurationResponseConfigurations struct {
	value *ConfigurationResponseConfigurations
	isSet bool
}

func (v NullableConfigurationResponseConfigurations) Get() *ConfigurationResponseConfigurations {
	return v.value
}

func (v *NullableConfigurationResponseConfigurations) Set(val *ConfigurationResponseConfigurations) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationResponseConfigurations) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationResponseConfigurations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationResponseConfigurations(val *ConfigurationResponseConfigurations) *NullableConfigurationResponseConfigurations {
	return &NullableConfigurationResponseConfigurations{value: val, isSet: true}
}

func (v NullableConfigurationResponseConfigurations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationResponseConfigurations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
