/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpdateAgentKindVersionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAgentKindVersionRequest{}

// UpdateAgentKindVersionRequest struct for UpdateAgentKindVersionRequest
type UpdateAgentKindVersionRequest struct {
	// Target agent kind version to upgrade to (e.g. \"2.0.0\")
	Version string `json:"version"`
	// Environment variables to apply during the upgrade deployment
	Env []EnvironmentVariable `json:"env,omitempty"`
	// Enable auto instrumentation for observability
	EnableAutoInstrumentation *bool `json:"enableAutoInstrumentation,omitempty"`
}

// NewUpdateAgentKindVersionRequest instantiates a new UpdateAgentKindVersionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAgentKindVersionRequest(version string) *UpdateAgentKindVersionRequest {
	this := UpdateAgentKindVersionRequest{}
	this.Version = version
	return &this
}

// NewUpdateAgentKindVersionRequestWithDefaults instantiates a new UpdateAgentKindVersionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAgentKindVersionRequestWithDefaults() *UpdateAgentKindVersionRequest {
	this := UpdateAgentKindVersionRequest{}
	return &this
}

// GetVersion returns the Version field value
func (o *UpdateAgentKindVersionRequest) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *UpdateAgentKindVersionRequest) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *UpdateAgentKindVersionRequest) SetVersion(v string) {
	o.Version = v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *UpdateAgentKindVersionRequest) GetEnv() []EnvironmentVariable {
	if o == nil || IsNil(o.Env) {
		var ret []EnvironmentVariable
		return ret
	}
	return o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAgentKindVersionRequest) GetEnvOk() ([]EnvironmentVariable, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *UpdateAgentKindVersionRequest) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given []EnvironmentVariable and assigns it to the Env field.
func (o *UpdateAgentKindVersionRequest) SetEnv(v []EnvironmentVariable) {
	o.Env = v
}

// GetEnableAutoInstrumentation returns the EnableAutoInstrumentation field value if set, zero value otherwise.
func (o *UpdateAgentKindVersionRequest) GetEnableAutoInstrumentation() bool {
	if o == nil || IsNil(o.EnableAutoInstrumentation) {
		var ret bool
		return ret
	}
	return *o.EnableAutoInstrumentation
}

// GetEnableAutoInstrumentationOk returns a tuple with the EnableAutoInstrumentation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAgentKindVersionRequest) GetEnableAutoInstrumentationOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableAutoInstrumentation) {
		return nil, false
	}
	return o.EnableAutoInstrumentation, true
}

// HasEnableAutoInstrumentation returns a boolean if a field has been set.
func (o *UpdateAgentKindVersionRequest) HasEnableAutoInstrumentation() bool {
	if o != nil && !IsNil(o.EnableAutoInstrumentation) {
		return true
	}

	return false
}

// SetEnableAutoInstrumentation gets a reference to the given bool and assigns it to the EnableAutoInstrumentation field.
func (o *UpdateAgentKindVersionRequest) SetEnableAutoInstrumentation(v bool) {
	o.EnableAutoInstrumentation = &v
}

func (o UpdateAgentKindVersionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAgentKindVersionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.EnableAutoInstrumentation) {
		toSerialize["enableAutoInstrumentation"] = o.EnableAutoInstrumentation
	}
	return toSerialize, nil
}

type NullableUpdateAgentKindVersionRequest struct {
	value *UpdateAgentKindVersionRequest
	isSet bool
}

func (v NullableUpdateAgentKindVersionRequest) Get() *UpdateAgentKindVersionRequest {
	return v.value
}

func (v *NullableUpdateAgentKindVersionRequest) Set(val *UpdateAgentKindVersionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAgentKindVersionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAgentKindVersionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAgentKindVersionRequest(val *UpdateAgentKindVersionRequest) *NullableUpdateAgentKindVersionRequest {
	return &NullableUpdateAgentKindVersionRequest{value: val, isSet: true}
}

func (v NullableUpdateAgentKindVersionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAgentKindVersionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
