/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the CreateAgentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAgentRequest{}

// CreateAgentRequest Create an agent. For internal provisioning, supply either repository (source build) or agentKind (from a published Kind version).
type CreateAgentRequest struct {
	// Unique name of the agent
	Name string `json:"name"`
	// Display name of the agent
	DisplayName  string       `json:"displayName"`
	Provisioning Provisioning `json:"provisioning"`
	// Description of the agent
	Description    *string         `json:"description,omitempty"`
	AgentType      *AgentType      `json:"agentType,omitempty"`
	Build          *Build          `json:"build,omitempty"`
	Configurations *Configurations `json:"configurations,omitempty"`
	InputInterface *InputInterface `json:"inputInterface,omitempty"`
	// Optional LLM configurations to create atomically with the agent. Applied to the component's initial (lowest) environment. Name and type are auto-generated.
	ModelConfig []ModelConfigRequest `json:"modelConfig,omitempty"`
}

// NewCreateAgentRequest instantiates a new CreateAgentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAgentRequest(name string, displayName string, provisioning Provisioning) *CreateAgentRequest {
	this := CreateAgentRequest{}
	this.Name = name
	this.DisplayName = displayName
	this.Provisioning = provisioning
	return &this
}

// NewCreateAgentRequestWithDefaults instantiates a new CreateAgentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAgentRequestWithDefaults() *CreateAgentRequest {
	this := CreateAgentRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateAgentRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAgentRequest) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *CreateAgentRequest) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *CreateAgentRequest) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetProvisioning returns the Provisioning field value
func (o *CreateAgentRequest) GetProvisioning() Provisioning {
	if o == nil {
		var ret Provisioning
		return ret
	}

	return o.Provisioning
}

// GetProvisioningOk returns a tuple with the Provisioning field value
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetProvisioningOk() (*Provisioning, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provisioning, true
}

// SetProvisioning sets field value
func (o *CreateAgentRequest) SetProvisioning(v Provisioning) {
	o.Provisioning = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateAgentRequest) SetDescription(v string) {
	o.Description = &v
}

// GetAgentType returns the AgentType field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetAgentType() AgentType {
	if o == nil || IsNil(o.AgentType) {
		var ret AgentType
		return ret
	}
	return *o.AgentType
}

// GetAgentTypeOk returns a tuple with the AgentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetAgentTypeOk() (*AgentType, bool) {
	if o == nil || IsNil(o.AgentType) {
		return nil, false
	}
	return o.AgentType, true
}

// HasAgentType returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasAgentType() bool {
	if o != nil && !IsNil(o.AgentType) {
		return true
	}

	return false
}

// SetAgentType gets a reference to the given AgentType and assigns it to the AgentType field.
func (o *CreateAgentRequest) SetAgentType(v AgentType) {
	o.AgentType = &v
}

// GetBuild returns the Build field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetBuild() Build {
	if o == nil || IsNil(o.Build) {
		var ret Build
		return ret
	}
	return *o.Build
}

// GetBuildOk returns a tuple with the Build field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetBuildOk() (*Build, bool) {
	if o == nil || IsNil(o.Build) {
		return nil, false
	}
	return o.Build, true
}

// HasBuild returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasBuild() bool {
	if o != nil && !IsNil(o.Build) {
		return true
	}

	return false
}

// SetBuild gets a reference to the given Build and assigns it to the Build field.
func (o *CreateAgentRequest) SetBuild(v Build) {
	o.Build = &v
}

// GetConfigurations returns the Configurations field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetConfigurations() Configurations {
	if o == nil || IsNil(o.Configurations) {
		var ret Configurations
		return ret
	}
	return *o.Configurations
}

// GetConfigurationsOk returns a tuple with the Configurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetConfigurationsOk() (*Configurations, bool) {
	if o == nil || IsNil(o.Configurations) {
		return nil, false
	}
	return o.Configurations, true
}

// HasConfigurations returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasConfigurations() bool {
	if o != nil && !IsNil(o.Configurations) {
		return true
	}

	return false
}

// SetConfigurations gets a reference to the given Configurations and assigns it to the Configurations field.
func (o *CreateAgentRequest) SetConfigurations(v Configurations) {
	o.Configurations = &v
}

// GetInputInterface returns the InputInterface field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetInputInterface() InputInterface {
	if o == nil || IsNil(o.InputInterface) {
		var ret InputInterface
		return ret
	}
	return *o.InputInterface
}

// GetInputInterfaceOk returns a tuple with the InputInterface field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetInputInterfaceOk() (*InputInterface, bool) {
	if o == nil || IsNil(o.InputInterface) {
		return nil, false
	}
	return o.InputInterface, true
}

// HasInputInterface returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasInputInterface() bool {
	if o != nil && !IsNil(o.InputInterface) {
		return true
	}

	return false
}

// SetInputInterface gets a reference to the given InputInterface and assigns it to the InputInterface field.
func (o *CreateAgentRequest) SetInputInterface(v InputInterface) {
	o.InputInterface = &v
}

// GetModelConfig returns the ModelConfig field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetModelConfig() []ModelConfigRequest {
	if o == nil || IsNil(o.ModelConfig) {
		var ret []ModelConfigRequest
		return ret
	}
	return o.ModelConfig
}

// GetModelConfigOk returns a tuple with the ModelConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetModelConfigOk() ([]ModelConfigRequest, bool) {
	if o == nil || IsNil(o.ModelConfig) {
		return nil, false
	}
	return o.ModelConfig, true
}

// HasModelConfig returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasModelConfig() bool {
	if o != nil && !IsNil(o.ModelConfig) {
		return true
	}

	return false
}

// SetModelConfig gets a reference to the given []ModelConfigRequest and assigns it to the ModelConfig field.
func (o *CreateAgentRequest) SetModelConfig(v []ModelConfigRequest) {
	o.ModelConfig = v
}

func (o CreateAgentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAgentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	toSerialize["provisioning"] = o.Provisioning
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.AgentType) {
		toSerialize["agentType"] = o.AgentType
	}
	if !IsNil(o.Build) {
		toSerialize["build"] = o.Build
	}
	if !IsNil(o.Configurations) {
		toSerialize["configurations"] = o.Configurations
	}
	if !IsNil(o.InputInterface) {
		toSerialize["inputInterface"] = o.InputInterface
	}
	if !IsNil(o.ModelConfig) {
		toSerialize["modelConfig"] = o.ModelConfig
	}
	return toSerialize, nil
}

type NullableCreateAgentRequest struct {
	value *CreateAgentRequest
	isSet bool
}

func (v NullableCreateAgentRequest) Get() *CreateAgentRequest {
	return v.value
}

func (v *NullableCreateAgentRequest) Set(val *CreateAgentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAgentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAgentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAgentRequest(val *CreateAgentRequest) *NullableCreateAgentRequest {
	return &NullableCreateAgentRequest{value: val, isSet: true}
}

func (v NullableCreateAgentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAgentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
