/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the KindPublishStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KindPublishStatusResponse{}

// KindPublishStatusResponse struct for KindPublishStatusResponse
type KindPublishStatusResponse struct {
	// Whether this build's image is already published as a kind version
	IsPublished bool `json:"isPublished"`
	// Name of the kind it was published under (only present when isPublished is true)
	KindName *string `json:"kindName,omitempty"`
	// Version it was published as (only present when isPublished is true)
	Version *string `json:"version,omitempty"`
}

// NewKindPublishStatusResponse instantiates a new KindPublishStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKindPublishStatusResponse(isPublished bool) *KindPublishStatusResponse {
	this := KindPublishStatusResponse{}
	this.IsPublished = isPublished
	return &this
}

// NewKindPublishStatusResponseWithDefaults instantiates a new KindPublishStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKindPublishStatusResponseWithDefaults() *KindPublishStatusResponse {
	this := KindPublishStatusResponse{}
	return &this
}

// GetIsPublished returns the IsPublished field value
func (o *KindPublishStatusResponse) GetIsPublished() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPublished
}

// GetIsPublishedOk returns a tuple with the IsPublished field value
// and a boolean to check if the value has been set.
func (o *KindPublishStatusResponse) GetIsPublishedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPublished, true
}

// SetIsPublished sets field value
func (o *KindPublishStatusResponse) SetIsPublished(v bool) {
	o.IsPublished = v
}

// GetKindName returns the KindName field value if set, zero value otherwise.
func (o *KindPublishStatusResponse) GetKindName() string {
	if o == nil || IsNil(o.KindName) {
		var ret string
		return ret
	}
	return *o.KindName
}

// GetKindNameOk returns a tuple with the KindName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KindPublishStatusResponse) GetKindNameOk() (*string, bool) {
	if o == nil || IsNil(o.KindName) {
		return nil, false
	}
	return o.KindName, true
}

// HasKindName returns a boolean if a field has been set.
func (o *KindPublishStatusResponse) HasKindName() bool {
	if o != nil && !IsNil(o.KindName) {
		return true
	}

	return false
}

// SetKindName gets a reference to the given string and assigns it to the KindName field.
func (o *KindPublishStatusResponse) SetKindName(v string) {
	o.KindName = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *KindPublishStatusResponse) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KindPublishStatusResponse) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *KindPublishStatusResponse) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *KindPublishStatusResponse) SetVersion(v string) {
	o.Version = &v
}

func (o KindPublishStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KindPublishStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isPublished"] = o.IsPublished
	if !IsNil(o.KindName) {
		toSerialize["kindName"] = o.KindName
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableKindPublishStatusResponse struct {
	value *KindPublishStatusResponse
	isSet bool
}

func (v NullableKindPublishStatusResponse) Get() *KindPublishStatusResponse {
	return v.value
}

func (v *NullableKindPublishStatusResponse) Set(val *KindPublishStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKindPublishStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKindPublishStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKindPublishStatusResponse(val *KindPublishStatusResponse) *NullableKindPublishStatusResponse {
	return &NullableKindPublishStatusResponse{value: val, isSet: true}
}

func (v NullableKindPublishStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKindPublishStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
