/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the AgentKindVersionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentKindVersionResponse{}

// AgentKindVersionResponse struct for AgentKindVersionResponse
type AgentKindVersionResponse struct {
	// Version tag
	Version string `json:"version"`
	// Build name from the source agent used to publish this version
	BuildName *string `json:"buildName,omitempty"`
	// Docker image ID for this version. A kind version is only created once the source build completes successfully with an image.
	ImageId string `json:"imageId"`
	// Name of the agent this version was published from
	SourceAgentName string `json:"sourceAgentName"`
	// Project the source agent belongs to
	SourceProjectName string `json:"sourceProjectName"`
	// Agent sub-type (chat-api or custom-api)
	AgentSubType *string `json:"agentSubType,omitempty"`
	// Configuration schema defining the parameters users must supply when creating an agent from this kind
	ConfigSchema []AgentKindConfigSchemaItem `json:"configSchema"`
	// Optional interface metadata for this version (e.g. OpenAPI spec). Only returned on single-version fetch.
	Metadata  map[string]interface{} `json:"metadata,omitempty"`
	CreatedAt time.Time              `json:"createdAt"`
}

// NewAgentKindVersionResponse instantiates a new AgentKindVersionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentKindVersionResponse(version string, imageId string, sourceAgentName string, sourceProjectName string, configSchema []AgentKindConfigSchemaItem, createdAt time.Time) *AgentKindVersionResponse {
	this := AgentKindVersionResponse{}
	this.Version = version
	this.ImageId = imageId
	this.SourceAgentName = sourceAgentName
	this.SourceProjectName = sourceProjectName
	this.ConfigSchema = configSchema
	this.CreatedAt = createdAt
	return &this
}

// NewAgentKindVersionResponseWithDefaults instantiates a new AgentKindVersionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentKindVersionResponseWithDefaults() *AgentKindVersionResponse {
	this := AgentKindVersionResponse{}
	return &this
}

// GetVersion returns the Version field value
func (o *AgentKindVersionResponse) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *AgentKindVersionResponse) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *AgentKindVersionResponse) SetVersion(v string) {
	o.Version = v
}

// GetBuildName returns the BuildName field value if set, zero value otherwise.
func (o *AgentKindVersionResponse) GetBuildName() string {
	if o == nil || IsNil(o.BuildName) {
		var ret string
		return ret
	}
	return *o.BuildName
}

// GetBuildNameOk returns a tuple with the BuildName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentKindVersionResponse) GetBuildNameOk() (*string, bool) {
	if o == nil || IsNil(o.BuildName) {
		return nil, false
	}
	return o.BuildName, true
}

// HasBuildName returns a boolean if a field has been set.
func (o *AgentKindVersionResponse) HasBuildName() bool {
	if o != nil && !IsNil(o.BuildName) {
		return true
	}

	return false
}

// SetBuildName gets a reference to the given string and assigns it to the BuildName field.
func (o *AgentKindVersionResponse) SetBuildName(v string) {
	o.BuildName = &v
}

// GetImageId returns the ImageId field value
func (o *AgentKindVersionResponse) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *AgentKindVersionResponse) GetImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *AgentKindVersionResponse) SetImageId(v string) {
	o.ImageId = v
}

// GetSourceAgentName returns the SourceAgentName field value
func (o *AgentKindVersionResponse) GetSourceAgentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceAgentName
}

// GetSourceAgentNameOk returns a tuple with the SourceAgentName field value
// and a boolean to check if the value has been set.
func (o *AgentKindVersionResponse) GetSourceAgentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceAgentName, true
}

// SetSourceAgentName sets field value
func (o *AgentKindVersionResponse) SetSourceAgentName(v string) {
	o.SourceAgentName = v
}

// GetSourceProjectName returns the SourceProjectName field value
func (o *AgentKindVersionResponse) GetSourceProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceProjectName
}

// GetSourceProjectNameOk returns a tuple with the SourceProjectName field value
// and a boolean to check if the value has been set.
func (o *AgentKindVersionResponse) GetSourceProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceProjectName, true
}

// SetSourceProjectName sets field value
func (o *AgentKindVersionResponse) SetSourceProjectName(v string) {
	o.SourceProjectName = v
}

// GetAgentSubType returns the AgentSubType field value if set, zero value otherwise.
func (o *AgentKindVersionResponse) GetAgentSubType() string {
	if o == nil || IsNil(o.AgentSubType) {
		var ret string
		return ret
	}
	return *o.AgentSubType
}

// GetAgentSubTypeOk returns a tuple with the AgentSubType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentKindVersionResponse) GetAgentSubTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AgentSubType) {
		return nil, false
	}
	return o.AgentSubType, true
}

// HasAgentSubType returns a boolean if a field has been set.
func (o *AgentKindVersionResponse) HasAgentSubType() bool {
	if o != nil && !IsNil(o.AgentSubType) {
		return true
	}

	return false
}

// SetAgentSubType gets a reference to the given string and assigns it to the AgentSubType field.
func (o *AgentKindVersionResponse) SetAgentSubType(v string) {
	o.AgentSubType = &v
}

// GetConfigSchema returns the ConfigSchema field value
func (o *AgentKindVersionResponse) GetConfigSchema() []AgentKindConfigSchemaItem {
	if o == nil {
		var ret []AgentKindConfigSchemaItem
		return ret
	}

	return o.ConfigSchema
}

// GetConfigSchemaOk returns a tuple with the ConfigSchema field value
// and a boolean to check if the value has been set.
func (o *AgentKindVersionResponse) GetConfigSchemaOk() ([]AgentKindConfigSchemaItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfigSchema, true
}

// SetConfigSchema sets field value
func (o *AgentKindVersionResponse) SetConfigSchema(v []AgentKindConfigSchemaItem) {
	o.ConfigSchema = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentKindVersionResponse) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentKindVersionResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *AgentKindVersionResponse) HasMetadata() bool {
	if o != nil && IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *AgentKindVersionResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AgentKindVersionResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AgentKindVersionResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AgentKindVersionResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o AgentKindVersionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentKindVersionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	if !IsNil(o.BuildName) {
		toSerialize["buildName"] = o.BuildName
	}
	toSerialize["imageId"] = o.ImageId
	toSerialize["sourceAgentName"] = o.SourceAgentName
	toSerialize["sourceProjectName"] = o.SourceProjectName
	if !IsNil(o.AgentSubType) {
		toSerialize["agentSubType"] = o.AgentSubType
	}
	toSerialize["configSchema"] = o.ConfigSchema
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

type NullableAgentKindVersionResponse struct {
	value *AgentKindVersionResponse
	isSet bool
}

func (v NullableAgentKindVersionResponse) Get() *AgentKindVersionResponse {
	return v.value
}

func (v *NullableAgentKindVersionResponse) Set(val *AgentKindVersionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentKindVersionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentKindVersionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentKindVersionResponse(val *AgentKindVersionResponse) *NullableAgentKindVersionResponse {
	return &NullableAgentKindVersionResponse{value: val, isSet: true}
}

func (v NullableAgentKindVersionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentKindVersionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
