/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the IdentityProviderListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentityProviderListResponse{}

// IdentityProviderListResponse struct for IdentityProviderListResponse
type IdentityProviderListResponse struct {
	// Number of identity providers in this response
	Count int32 `json:"count"`
	// List of identity providers
	List []IdentityProvider `json:"list"`
}

// NewIdentityProviderListResponse instantiates a new IdentityProviderListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityProviderListResponse(count int32, list []IdentityProvider) *IdentityProviderListResponse {
	this := IdentityProviderListResponse{}
	this.Count = count
	this.List = list
	return &this
}

// NewIdentityProviderListResponseWithDefaults instantiates a new IdentityProviderListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityProviderListResponseWithDefaults() *IdentityProviderListResponse {
	this := IdentityProviderListResponse{}
	return &this
}

// GetCount returns the Count field value
func (o *IdentityProviderListResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *IdentityProviderListResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *IdentityProviderListResponse) SetCount(v int32) {
	o.Count = v
}

// GetList returns the List field value
func (o *IdentityProviderListResponse) GetList() []IdentityProvider {
	if o == nil {
		var ret []IdentityProvider
		return ret
	}

	return o.List
}

// GetListOk returns a tuple with the List field value
// and a boolean to check if the value has been set.
func (o *IdentityProviderListResponse) GetListOk() ([]IdentityProvider, bool) {
	if o == nil {
		return nil, false
	}
	return o.List, true
}

// SetList sets field value
func (o *IdentityProviderListResponse) SetList(v []IdentityProvider) {
	o.List = v
}

func (o IdentityProviderListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentityProviderListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["list"] = o.List
	return toSerialize, nil
}

type NullableIdentityProviderListResponse struct {
	value *IdentityProviderListResponse
	isSet bool
}

func (v NullableIdentityProviderListResponse) Get() *IdentityProviderListResponse {
	return v.value
}

func (v *NullableIdentityProviderListResponse) Set(val *IdentityProviderListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityProviderListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityProviderListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityProviderListResponse(val *IdentityProviderListResponse) *NullableIdentityProviderListResponse {
	return &NullableIdentityProviderListResponse{value: val, isSet: true}
}

func (v NullableIdentityProviderListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityProviderListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
