/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the StoredAPIKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoredAPIKey{}

// StoredAPIKey struct for StoredAPIKey
type StoredAPIKey struct {
	// Stable API key identifier.
	Uuid string `json:"uuid"`
	// Unique name of the API key within the agent.
	Name string `json:"name"`
	// Human-readable name shown in the console.
	DisplayName string `json:"displayName"`
	// UUID of the artifact this key is bound to.
	ArtifactUuid string `json:"artifactUuid"`
	// Organization name the key belongs to.
	OrganizationName string `json:"organizationName"`
	// Masked representation of the API key (full value is shown only once at creation).
	MaskedApiKey string `json:"maskedApiKey"`
	// Current lifecycle status of the API key (e.g. active, revoked).
	Status string `json:"status"`
	// Internal purpose code of the API key.
	Purpose   int32     `json:"purpose"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	// Expiration timestamp if set.
	ExpiresAt NullableTime `json:"expiresAt,omitempty"`
}

// NewStoredAPIKey instantiates a new StoredAPIKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoredAPIKey(uuid string, name string, displayName string, artifactUuid string, organizationName string, maskedApiKey string, status string, purpose int32, createdAt time.Time, updatedAt time.Time) *StoredAPIKey {
	this := StoredAPIKey{}
	this.Uuid = uuid
	this.Name = name
	this.DisplayName = displayName
	this.ArtifactUuid = artifactUuid
	this.OrganizationName = organizationName
	this.MaskedApiKey = maskedApiKey
	this.Status = status
	this.Purpose = purpose
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewStoredAPIKeyWithDefaults instantiates a new StoredAPIKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoredAPIKeyWithDefaults() *StoredAPIKey {
	this := StoredAPIKey{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *StoredAPIKey) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *StoredAPIKey) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *StoredAPIKey) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *StoredAPIKey) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StoredAPIKey) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StoredAPIKey) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *StoredAPIKey) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *StoredAPIKey) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *StoredAPIKey) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetArtifactUuid returns the ArtifactUuid field value
func (o *StoredAPIKey) GetArtifactUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArtifactUuid
}

// GetArtifactUuidOk returns a tuple with the ArtifactUuid field value
// and a boolean to check if the value has been set.
func (o *StoredAPIKey) GetArtifactUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArtifactUuid, true
}

// SetArtifactUuid sets field value
func (o *StoredAPIKey) SetArtifactUuid(v string) {
	o.ArtifactUuid = v
}

// GetOrganizationName returns the OrganizationName field value
func (o *StoredAPIKey) GetOrganizationName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationName
}

// GetOrganizationNameOk returns a tuple with the OrganizationName field value
// and a boolean to check if the value has been set.
func (o *StoredAPIKey) GetOrganizationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationName, true
}

// SetOrganizationName sets field value
func (o *StoredAPIKey) SetOrganizationName(v string) {
	o.OrganizationName = v
}

// GetMaskedApiKey returns the MaskedApiKey field value
func (o *StoredAPIKey) GetMaskedApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaskedApiKey
}

// GetMaskedApiKeyOk returns a tuple with the MaskedApiKey field value
// and a boolean to check if the value has been set.
func (o *StoredAPIKey) GetMaskedApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaskedApiKey, true
}

// SetMaskedApiKey sets field value
func (o *StoredAPIKey) SetMaskedApiKey(v string) {
	o.MaskedApiKey = v
}

// GetStatus returns the Status field value
func (o *StoredAPIKey) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *StoredAPIKey) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *StoredAPIKey) SetStatus(v string) {
	o.Status = v
}

// GetPurpose returns the Purpose field value
func (o *StoredAPIKey) GetPurpose() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Purpose
}

// GetPurposeOk returns a tuple with the Purpose field value
// and a boolean to check if the value has been set.
func (o *StoredAPIKey) GetPurposeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Purpose, true
}

// SetPurpose sets field value
func (o *StoredAPIKey) SetPurpose(v int32) {
	o.Purpose = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *StoredAPIKey) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *StoredAPIKey) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *StoredAPIKey) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *StoredAPIKey) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *StoredAPIKey) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *StoredAPIKey) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoredAPIKey) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoredAPIKey) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *StoredAPIKey) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *StoredAPIKey) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}

// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *StoredAPIKey) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *StoredAPIKey) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

func (o StoredAPIKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoredAPIKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	toSerialize["artifactUuid"] = o.ArtifactUuid
	toSerialize["organizationName"] = o.OrganizationName
	toSerialize["maskedApiKey"] = o.MaskedApiKey
	toSerialize["status"] = o.Status
	toSerialize["purpose"] = o.Purpose
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	if o.ExpiresAt.IsSet() {
		toSerialize["expiresAt"] = o.ExpiresAt.Get()
	}
	return toSerialize, nil
}

type NullableStoredAPIKey struct {
	value *StoredAPIKey
	isSet bool
}

func (v NullableStoredAPIKey) Get() *StoredAPIKey {
	return v.value
}

func (v *NullableStoredAPIKey) Set(val *StoredAPIKey) {
	v.value = val
	v.isSet = true
}

func (v NullableStoredAPIKey) IsSet() bool {
	return v.isSet
}

func (v *NullableStoredAPIKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoredAPIKey(val *StoredAPIKey) *NullableStoredAPIKey {
	return &NullableStoredAPIKey{value: val, isSet: true}
}

func (v NullableStoredAPIKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoredAPIKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
