/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the CORSConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CORSConfig{}

// CORSConfig struct for CORSConfig
type CORSConfig struct {
	// Enable or disable CORS for this agent endpoint
	Enabled *bool `json:"enabled,omitempty"`
	// Allowed origins. Use [\"*\"] to allow all (incompatible with allowCredentials)
	AllowOrigin []string `json:"allowOrigin,omitempty"`
	// Allowed HTTP methods for CORS
	AllowMethods []string `json:"allowMethods,omitempty"`
	// Allowed request headers for CORS
	AllowHeaders []string `json:"allowHeaders,omitempty"`
	// Whether credentials are allowed. Cannot be true when allowOrigin contains \"*\"
	AllowCredentials *bool `json:"allowCredentials,omitempty"`
}

// NewCORSConfig instantiates a new CORSConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCORSConfig() *CORSConfig {
	this := CORSConfig{}
	var enabled bool = true
	this.Enabled = &enabled
	var allowCredentials bool = false
	this.AllowCredentials = &allowCredentials
	return &this
}

// NewCORSConfigWithDefaults instantiates a new CORSConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCORSConfigWithDefaults() *CORSConfig {
	this := CORSConfig{}
	var enabled bool = true
	this.Enabled = &enabled
	var allowCredentials bool = false
	this.AllowCredentials = &allowCredentials
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CORSConfig) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CORSConfig) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CORSConfig) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CORSConfig) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetAllowOrigin returns the AllowOrigin field value if set, zero value otherwise.
func (o *CORSConfig) GetAllowOrigin() []string {
	if o == nil || IsNil(o.AllowOrigin) {
		var ret []string
		return ret
	}
	return o.AllowOrigin
}

// GetAllowOriginOk returns a tuple with the AllowOrigin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CORSConfig) GetAllowOriginOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowOrigin) {
		return nil, false
	}
	return o.AllowOrigin, true
}

// HasAllowOrigin returns a boolean if a field has been set.
func (o *CORSConfig) HasAllowOrigin() bool {
	if o != nil && !IsNil(o.AllowOrigin) {
		return true
	}

	return false
}

// SetAllowOrigin gets a reference to the given []string and assigns it to the AllowOrigin field.
func (o *CORSConfig) SetAllowOrigin(v []string) {
	o.AllowOrigin = v
}

// GetAllowMethods returns the AllowMethods field value if set, zero value otherwise.
func (o *CORSConfig) GetAllowMethods() []string {
	if o == nil || IsNil(o.AllowMethods) {
		var ret []string
		return ret
	}
	return o.AllowMethods
}

// GetAllowMethodsOk returns a tuple with the AllowMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CORSConfig) GetAllowMethodsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowMethods) {
		return nil, false
	}
	return o.AllowMethods, true
}

// HasAllowMethods returns a boolean if a field has been set.
func (o *CORSConfig) HasAllowMethods() bool {
	if o != nil && !IsNil(o.AllowMethods) {
		return true
	}

	return false
}

// SetAllowMethods gets a reference to the given []string and assigns it to the AllowMethods field.
func (o *CORSConfig) SetAllowMethods(v []string) {
	o.AllowMethods = v
}

// GetAllowHeaders returns the AllowHeaders field value if set, zero value otherwise.
func (o *CORSConfig) GetAllowHeaders() []string {
	if o == nil || IsNil(o.AllowHeaders) {
		var ret []string
		return ret
	}
	return o.AllowHeaders
}

// GetAllowHeadersOk returns a tuple with the AllowHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CORSConfig) GetAllowHeadersOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowHeaders) {
		return nil, false
	}
	return o.AllowHeaders, true
}

// HasAllowHeaders returns a boolean if a field has been set.
func (o *CORSConfig) HasAllowHeaders() bool {
	if o != nil && !IsNil(o.AllowHeaders) {
		return true
	}

	return false
}

// SetAllowHeaders gets a reference to the given []string and assigns it to the AllowHeaders field.
func (o *CORSConfig) SetAllowHeaders(v []string) {
	o.AllowHeaders = v
}

// GetAllowCredentials returns the AllowCredentials field value if set, zero value otherwise.
func (o *CORSConfig) GetAllowCredentials() bool {
	if o == nil || IsNil(o.AllowCredentials) {
		var ret bool
		return ret
	}
	return *o.AllowCredentials
}

// GetAllowCredentialsOk returns a tuple with the AllowCredentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CORSConfig) GetAllowCredentialsOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowCredentials) {
		return nil, false
	}
	return o.AllowCredentials, true
}

// HasAllowCredentials returns a boolean if a field has been set.
func (o *CORSConfig) HasAllowCredentials() bool {
	if o != nil && !IsNil(o.AllowCredentials) {
		return true
	}

	return false
}

// SetAllowCredentials gets a reference to the given bool and assigns it to the AllowCredentials field.
func (o *CORSConfig) SetAllowCredentials(v bool) {
	o.AllowCredentials = &v
}

func (o CORSConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CORSConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.AllowOrigin) {
		toSerialize["allowOrigin"] = o.AllowOrigin
	}
	if !IsNil(o.AllowMethods) {
		toSerialize["allowMethods"] = o.AllowMethods
	}
	if !IsNil(o.AllowHeaders) {
		toSerialize["allowHeaders"] = o.AllowHeaders
	}
	if !IsNil(o.AllowCredentials) {
		toSerialize["allowCredentials"] = o.AllowCredentials
	}
	return toSerialize, nil
}

type NullableCORSConfig struct {
	value *CORSConfig
	isSet bool
}

func (v NullableCORSConfig) Get() *CORSConfig {
	return v.value
}

func (v *NullableCORSConfig) Set(val *CORSConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableCORSConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableCORSConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCORSConfig(val *CORSConfig) *NullableCORSConfig {
	return &NullableCORSConfig{value: val, isSet: true}
}

func (v NullableCORSConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCORSConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
