/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ThunderUrlRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThunderUrlRequest{}

// ThunderUrlRequest Registers an environment's env-Thunder origin via exactly one of two mutually-exclusive fields — setting both is rejected with 400:  - `handle` (on-prem path): an unguessable label AMS resolves into the   full origin itself, replacing the predictable \"<org>-<env>\" pattern.   Optional — omit it (or send an empty string, with url also omitted)   to have the server generate one. - `url` (SaaS/control-plane path): the full origin the caller has   already provisioned, for deployments where different environments   can live under different domains and there is no single pattern AMS   could compute. AMS validates and stores it verbatim; the   environment's registration then has no handle at all.
type ThunderUrlRequest struct {
	// DNS-label-safe handle (lowercase alphanumeric with hyphens, no leading/trailing hyphen) that replaces \"<org>-<env>\" in \"<handle>.<baseDomain>\". Must be globally unique across all orgs/environments, and at least 3 characters. Omit to auto-generate a 10-character handle. Mutually exclusive with url.
	Handle *string `json:"handle,omitempty"`
	// The full env-Thunder origin (scheme + host, no path/query/fragment) this environment is already reachable at — the SaaS/control-plane path. Must be http or https, resolve to a public IP address (no private/loopback hosts), and be globally unique across all orgs/environments. Mutually exclusive with handle.
	Url *string `json:"url,omitempty"`
}

// NewThunderUrlRequest instantiates a new ThunderUrlRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThunderUrlRequest() *ThunderUrlRequest {
	this := ThunderUrlRequest{}
	return &this
}

// NewThunderUrlRequestWithDefaults instantiates a new ThunderUrlRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThunderUrlRequestWithDefaults() *ThunderUrlRequest {
	this := ThunderUrlRequest{}
	return &this
}

// GetHandle returns the Handle field value if set, zero value otherwise.
func (o *ThunderUrlRequest) GetHandle() string {
	if o == nil || IsNil(o.Handle) {
		var ret string
		return ret
	}
	return *o.Handle
}

// GetHandleOk returns a tuple with the Handle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThunderUrlRequest) GetHandleOk() (*string, bool) {
	if o == nil || IsNil(o.Handle) {
		return nil, false
	}
	return o.Handle, true
}

// HasHandle returns a boolean if a field has been set.
func (o *ThunderUrlRequest) HasHandle() bool {
	if o != nil && !IsNil(o.Handle) {
		return true
	}

	return false
}

// SetHandle gets a reference to the given string and assigns it to the Handle field.
func (o *ThunderUrlRequest) SetHandle(v string) {
	o.Handle = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ThunderUrlRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThunderUrlRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ThunderUrlRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ThunderUrlRequest) SetUrl(v string) {
	o.Url = &v
}

func (o ThunderUrlRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThunderUrlRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Handle) {
		toSerialize["handle"] = o.Handle
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableThunderUrlRequest struct {
	value *ThunderUrlRequest
	isSet bool
}

func (v NullableThunderUrlRequest) Get() *ThunderUrlRequest {
	return v.value
}

func (v *NullableThunderUrlRequest) Set(val *ThunderUrlRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableThunderUrlRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableThunderUrlRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThunderUrlRequest(val *ThunderUrlRequest) *NullableThunderUrlRequest {
	return &NullableThunderUrlRequest{value: val, isSet: true}
}

func (v NullableThunderUrlRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThunderUrlRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
