/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the DeployAgentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeployAgentRequest{}

// DeployAgentRequest struct for DeployAgentRequest
type DeployAgentRequest struct {
	// Container image ID to deploy
	ImageId string `json:"imageId"`
	// Environment variables
	Env []EnvironmentVariable `json:"env,omitempty"`
	// File mounts
	Files []FileMount `json:"files,omitempty"`
	// Enable auto instrumentation for observability
	EnableAutoInstrumentation *bool `json:"enableAutoInstrumentation,omitempty"`
	// Enable API key security for the agent endpoint
	EnableApiKeySecurity *bool       `json:"enableApiKeySecurity,omitempty"`
	CorsConfig           *CORSConfig `json:"corsConfig,omitempty"`
	// Enable OAuth security for the agent endpoint. Mutually exclusive with enableApiKeySecurity.
	EnableOAuthSecurity *bool        `json:"enableOAuthSecurity,omitempty"`
	OauthConfig         *OAuthConfig `json:"oauthConfig,omitempty"`
}

// NewDeployAgentRequest instantiates a new DeployAgentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeployAgentRequest(imageId string) *DeployAgentRequest {
	this := DeployAgentRequest{}
	this.ImageId = imageId
	var enableAutoInstrumentation bool = true
	this.EnableAutoInstrumentation = &enableAutoInstrumentation
	var enableApiKeySecurity bool = true
	this.EnableApiKeySecurity = &enableApiKeySecurity
	var enableOAuthSecurity bool = false
	this.EnableOAuthSecurity = &enableOAuthSecurity
	return &this
}

// NewDeployAgentRequestWithDefaults instantiates a new DeployAgentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeployAgentRequestWithDefaults() *DeployAgentRequest {
	this := DeployAgentRequest{}
	var enableAutoInstrumentation bool = true
	this.EnableAutoInstrumentation = &enableAutoInstrumentation
	var enableApiKeySecurity bool = true
	this.EnableApiKeySecurity = &enableApiKeySecurity
	var enableOAuthSecurity bool = false
	this.EnableOAuthSecurity = &enableOAuthSecurity
	return &this
}

// GetImageId returns the ImageId field value
func (o *DeployAgentRequest) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *DeployAgentRequest) GetImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *DeployAgentRequest) SetImageId(v string) {
	o.ImageId = v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *DeployAgentRequest) GetEnv() []EnvironmentVariable {
	if o == nil || IsNil(o.Env) {
		var ret []EnvironmentVariable
		return ret
	}
	return o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployAgentRequest) GetEnvOk() ([]EnvironmentVariable, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *DeployAgentRequest) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given []EnvironmentVariable and assigns it to the Env field.
func (o *DeployAgentRequest) SetEnv(v []EnvironmentVariable) {
	o.Env = v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *DeployAgentRequest) GetFiles() []FileMount {
	if o == nil || IsNil(o.Files) {
		var ret []FileMount
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployAgentRequest) GetFilesOk() ([]FileMount, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *DeployAgentRequest) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []FileMount and assigns it to the Files field.
func (o *DeployAgentRequest) SetFiles(v []FileMount) {
	o.Files = v
}

// GetEnableAutoInstrumentation returns the EnableAutoInstrumentation field value if set, zero value otherwise.
func (o *DeployAgentRequest) GetEnableAutoInstrumentation() bool {
	if o == nil || IsNil(o.EnableAutoInstrumentation) {
		var ret bool
		return ret
	}
	return *o.EnableAutoInstrumentation
}

// GetEnableAutoInstrumentationOk returns a tuple with the EnableAutoInstrumentation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployAgentRequest) GetEnableAutoInstrumentationOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableAutoInstrumentation) {
		return nil, false
	}
	return o.EnableAutoInstrumentation, true
}

// HasEnableAutoInstrumentation returns a boolean if a field has been set.
func (o *DeployAgentRequest) HasEnableAutoInstrumentation() bool {
	if o != nil && !IsNil(o.EnableAutoInstrumentation) {
		return true
	}

	return false
}

// SetEnableAutoInstrumentation gets a reference to the given bool and assigns it to the EnableAutoInstrumentation field.
func (o *DeployAgentRequest) SetEnableAutoInstrumentation(v bool) {
	o.EnableAutoInstrumentation = &v
}

// GetEnableApiKeySecurity returns the EnableApiKeySecurity field value if set, zero value otherwise.
func (o *DeployAgentRequest) GetEnableApiKeySecurity() bool {
	if o == nil || IsNil(o.EnableApiKeySecurity) {
		var ret bool
		return ret
	}
	return *o.EnableApiKeySecurity
}

// GetEnableApiKeySecurityOk returns a tuple with the EnableApiKeySecurity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployAgentRequest) GetEnableApiKeySecurityOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableApiKeySecurity) {
		return nil, false
	}
	return o.EnableApiKeySecurity, true
}

// HasEnableApiKeySecurity returns a boolean if a field has been set.
func (o *DeployAgentRequest) HasEnableApiKeySecurity() bool {
	if o != nil && !IsNil(o.EnableApiKeySecurity) {
		return true
	}

	return false
}

// SetEnableApiKeySecurity gets a reference to the given bool and assigns it to the EnableApiKeySecurity field.
func (o *DeployAgentRequest) SetEnableApiKeySecurity(v bool) {
	o.EnableApiKeySecurity = &v
}

// GetCorsConfig returns the CorsConfig field value if set, zero value otherwise.
func (o *DeployAgentRequest) GetCorsConfig() CORSConfig {
	if o == nil || IsNil(o.CorsConfig) {
		var ret CORSConfig
		return ret
	}
	return *o.CorsConfig
}

// GetCorsConfigOk returns a tuple with the CorsConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployAgentRequest) GetCorsConfigOk() (*CORSConfig, bool) {
	if o == nil || IsNil(o.CorsConfig) {
		return nil, false
	}
	return o.CorsConfig, true
}

// HasCorsConfig returns a boolean if a field has been set.
func (o *DeployAgentRequest) HasCorsConfig() bool {
	if o != nil && !IsNil(o.CorsConfig) {
		return true
	}

	return false
}

// SetCorsConfig gets a reference to the given CORSConfig and assigns it to the CorsConfig field.
func (o *DeployAgentRequest) SetCorsConfig(v CORSConfig) {
	o.CorsConfig = &v
}

// GetEnableOAuthSecurity returns the EnableOAuthSecurity field value if set, zero value otherwise.
func (o *DeployAgentRequest) GetEnableOAuthSecurity() bool {
	if o == nil || IsNil(o.EnableOAuthSecurity) {
		var ret bool
		return ret
	}
	return *o.EnableOAuthSecurity
}

// GetEnableOAuthSecurityOk returns a tuple with the EnableOAuthSecurity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployAgentRequest) GetEnableOAuthSecurityOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableOAuthSecurity) {
		return nil, false
	}
	return o.EnableOAuthSecurity, true
}

// HasEnableOAuthSecurity returns a boolean if a field has been set.
func (o *DeployAgentRequest) HasEnableOAuthSecurity() bool {
	if o != nil && !IsNil(o.EnableOAuthSecurity) {
		return true
	}

	return false
}

// SetEnableOAuthSecurity gets a reference to the given bool and assigns it to the EnableOAuthSecurity field.
func (o *DeployAgentRequest) SetEnableOAuthSecurity(v bool) {
	o.EnableOAuthSecurity = &v
}

// GetOauthConfig returns the OauthConfig field value if set, zero value otherwise.
func (o *DeployAgentRequest) GetOauthConfig() OAuthConfig {
	if o == nil || IsNil(o.OauthConfig) {
		var ret OAuthConfig
		return ret
	}
	return *o.OauthConfig
}

// GetOauthConfigOk returns a tuple with the OauthConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeployAgentRequest) GetOauthConfigOk() (*OAuthConfig, bool) {
	if o == nil || IsNil(o.OauthConfig) {
		return nil, false
	}
	return o.OauthConfig, true
}

// HasOauthConfig returns a boolean if a field has been set.
func (o *DeployAgentRequest) HasOauthConfig() bool {
	if o != nil && !IsNil(o.OauthConfig) {
		return true
	}

	return false
}

// SetOauthConfig gets a reference to the given OAuthConfig and assigns it to the OauthConfig field.
func (o *DeployAgentRequest) SetOauthConfig(v OAuthConfig) {
	o.OauthConfig = &v
}

func (o DeployAgentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeployAgentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["imageId"] = o.ImageId
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	if !IsNil(o.EnableAutoInstrumentation) {
		toSerialize["enableAutoInstrumentation"] = o.EnableAutoInstrumentation
	}
	if !IsNil(o.EnableApiKeySecurity) {
		toSerialize["enableApiKeySecurity"] = o.EnableApiKeySecurity
	}
	if !IsNil(o.CorsConfig) {
		toSerialize["corsConfig"] = o.CorsConfig
	}
	if !IsNil(o.EnableOAuthSecurity) {
		toSerialize["enableOAuthSecurity"] = o.EnableOAuthSecurity
	}
	if !IsNil(o.OauthConfig) {
		toSerialize["oauthConfig"] = o.OauthConfig
	}
	return toSerialize, nil
}

type NullableDeployAgentRequest struct {
	value *DeployAgentRequest
	isSet bool
}

func (v NullableDeployAgentRequest) Get() *DeployAgentRequest {
	return v.value
}

func (v *NullableDeployAgentRequest) Set(val *DeployAgentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeployAgentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeployAgentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeployAgentRequest(val *DeployAgentRequest) *NullableDeployAgentRequest {
	return &NullableDeployAgentRequest{value: val, isSet: true}
}

func (v NullableDeployAgentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeployAgentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
