/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the IdentityProvider type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentityProvider{}

// IdentityProvider A JWT identity provider (token issuer) configured on a gateway. Mirrors a gateway-side jwt-auth `system.keyManagers` entry. Only the fields needed to identify an issuer and validate its tokens are surfaced.
type IdentityProvider struct {
	// Unique identity provider name within the gateway (referenced as an issuer).
	Name string `json:"name"`
	// Expected `iss` claim value for tokens validated by this identity provider.
	Issuer *string `json:"issuer,omitempty"`
	// Remote JWKS endpoint used to fetch signing keys.
	JwksUri *string `json:"jwksUri,omitempty"`
	// Skip TLS verification when fetching the JWKS endpoint (testing/trusted internal only).
	SkipTlsVerify *bool `json:"skipTlsVerify,omitempty"`
	// Optional human-readable description (mirror-only).
	Description *string `json:"description,omitempty"`
	// Provenance of the identity provider. `system` providers (e.g. ThunderKeyManager) are seeded with the platform and cannot be deleted; `custom` providers are added by operators via the management script.
	Type *string `json:"type,omitempty"`
	// Environment this provider's gateway is mapped to (read-only, set on org-wide listing).
	EnvironmentName *string `json:"environmentName,omitempty"`
	// UUID of the gateway this provider is registered to (read-only, set on org-wide listing).
	GatewayId *string `json:"gatewayId,omitempty"`
	// Name of the gateway this provider is registered to (read-only, set on org-wide listing).
	GatewayName *string `json:"gatewayName,omitempty"`
}

// NewIdentityProvider instantiates a new IdentityProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityProvider(name string) *IdentityProvider {
	this := IdentityProvider{}
	this.Name = name
	var skipTlsVerify bool = false
	this.SkipTlsVerify = &skipTlsVerify
	var type_ string = "custom"
	this.Type = &type_
	return &this
}

// NewIdentityProviderWithDefaults instantiates a new IdentityProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityProviderWithDefaults() *IdentityProvider {
	this := IdentityProvider{}
	var skipTlsVerify bool = false
	this.SkipTlsVerify = &skipTlsVerify
	var type_ string = "custom"
	this.Type = &type_
	return &this
}

// GetName returns the Name field value
func (o *IdentityProvider) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IdentityProvider) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IdentityProvider) SetName(v string) {
	o.Name = v
}

// GetIssuer returns the Issuer field value if set, zero value otherwise.
func (o *IdentityProvider) GetIssuer() string {
	if o == nil || IsNil(o.Issuer) {
		var ret string
		return ret
	}
	return *o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityProvider) GetIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.Issuer) {
		return nil, false
	}
	return o.Issuer, true
}

// HasIssuer returns a boolean if a field has been set.
func (o *IdentityProvider) HasIssuer() bool {
	if o != nil && !IsNil(o.Issuer) {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given string and assigns it to the Issuer field.
func (o *IdentityProvider) SetIssuer(v string) {
	o.Issuer = &v
}

// GetJwksUri returns the JwksUri field value if set, zero value otherwise.
func (o *IdentityProvider) GetJwksUri() string {
	if o == nil || IsNil(o.JwksUri) {
		var ret string
		return ret
	}
	return *o.JwksUri
}

// GetJwksUriOk returns a tuple with the JwksUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityProvider) GetJwksUriOk() (*string, bool) {
	if o == nil || IsNil(o.JwksUri) {
		return nil, false
	}
	return o.JwksUri, true
}

// HasJwksUri returns a boolean if a field has been set.
func (o *IdentityProvider) HasJwksUri() bool {
	if o != nil && !IsNil(o.JwksUri) {
		return true
	}

	return false
}

// SetJwksUri gets a reference to the given string and assigns it to the JwksUri field.
func (o *IdentityProvider) SetJwksUri(v string) {
	o.JwksUri = &v
}

// GetSkipTlsVerify returns the SkipTlsVerify field value if set, zero value otherwise.
func (o *IdentityProvider) GetSkipTlsVerify() bool {
	if o == nil || IsNil(o.SkipTlsVerify) {
		var ret bool
		return ret
	}
	return *o.SkipTlsVerify
}

// GetSkipTlsVerifyOk returns a tuple with the SkipTlsVerify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityProvider) GetSkipTlsVerifyOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipTlsVerify) {
		return nil, false
	}
	return o.SkipTlsVerify, true
}

// HasSkipTlsVerify returns a boolean if a field has been set.
func (o *IdentityProvider) HasSkipTlsVerify() bool {
	if o != nil && !IsNil(o.SkipTlsVerify) {
		return true
	}

	return false
}

// SetSkipTlsVerify gets a reference to the given bool and assigns it to the SkipTlsVerify field.
func (o *IdentityProvider) SetSkipTlsVerify(v bool) {
	o.SkipTlsVerify = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *IdentityProvider) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityProvider) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *IdentityProvider) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *IdentityProvider) SetDescription(v string) {
	o.Description = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IdentityProvider) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityProvider) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IdentityProvider) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IdentityProvider) SetType(v string) {
	o.Type = &v
}

// GetEnvironmentName returns the EnvironmentName field value if set, zero value otherwise.
func (o *IdentityProvider) GetEnvironmentName() string {
	if o == nil || IsNil(o.EnvironmentName) {
		var ret string
		return ret
	}
	return *o.EnvironmentName
}

// GetEnvironmentNameOk returns a tuple with the EnvironmentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityProvider) GetEnvironmentNameOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentName) {
		return nil, false
	}
	return o.EnvironmentName, true
}

// HasEnvironmentName returns a boolean if a field has been set.
func (o *IdentityProvider) HasEnvironmentName() bool {
	if o != nil && !IsNil(o.EnvironmentName) {
		return true
	}

	return false
}

// SetEnvironmentName gets a reference to the given string and assigns it to the EnvironmentName field.
func (o *IdentityProvider) SetEnvironmentName(v string) {
	o.EnvironmentName = &v
}

// GetGatewayId returns the GatewayId field value if set, zero value otherwise.
func (o *IdentityProvider) GetGatewayId() string {
	if o == nil || IsNil(o.GatewayId) {
		var ret string
		return ret
	}
	return *o.GatewayId
}

// GetGatewayIdOk returns a tuple with the GatewayId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityProvider) GetGatewayIdOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayId) {
		return nil, false
	}
	return o.GatewayId, true
}

// HasGatewayId returns a boolean if a field has been set.
func (o *IdentityProvider) HasGatewayId() bool {
	if o != nil && !IsNil(o.GatewayId) {
		return true
	}

	return false
}

// SetGatewayId gets a reference to the given string and assigns it to the GatewayId field.
func (o *IdentityProvider) SetGatewayId(v string) {
	o.GatewayId = &v
}

// GetGatewayName returns the GatewayName field value if set, zero value otherwise.
func (o *IdentityProvider) GetGatewayName() string {
	if o == nil || IsNil(o.GatewayName) {
		var ret string
		return ret
	}
	return *o.GatewayName
}

// GetGatewayNameOk returns a tuple with the GatewayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityProvider) GetGatewayNameOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayName) {
		return nil, false
	}
	return o.GatewayName, true
}

// HasGatewayName returns a boolean if a field has been set.
func (o *IdentityProvider) HasGatewayName() bool {
	if o != nil && !IsNil(o.GatewayName) {
		return true
	}

	return false
}

// SetGatewayName gets a reference to the given string and assigns it to the GatewayName field.
func (o *IdentityProvider) SetGatewayName(v string) {
	o.GatewayName = &v
}

func (o IdentityProvider) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentityProvider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Issuer) {
		toSerialize["issuer"] = o.Issuer
	}
	if !IsNil(o.JwksUri) {
		toSerialize["jwksUri"] = o.JwksUri
	}
	if !IsNil(o.SkipTlsVerify) {
		toSerialize["skipTlsVerify"] = o.SkipTlsVerify
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.EnvironmentName) {
		toSerialize["environmentName"] = o.EnvironmentName
	}
	if !IsNil(o.GatewayId) {
		toSerialize["gatewayId"] = o.GatewayId
	}
	if !IsNil(o.GatewayName) {
		toSerialize["gatewayName"] = o.GatewayName
	}
	return toSerialize, nil
}

type NullableIdentityProvider struct {
	value *IdentityProvider
	isSet bool
}

func (v NullableIdentityProvider) Get() *IdentityProvider {
	return v.value
}

func (v *NullableIdentityProvider) Set(val *IdentityProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityProvider(val *IdentityProvider) *NullableIdentityProvider {
	return &NullableIdentityProvider{value: val, isSet: true}
}

func (v NullableIdentityProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
