/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the CreateEnvironmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEnvironmentRequest{}

// CreateEnvironmentRequest struct for CreateEnvironmentRequest
type CreateEnvironmentRequest struct {
	// Unique environment name (lowercase, alphanumeric with hyphens)
	Name string `json:"name"`
	// Human-readable display name
	DisplayName string `json:"displayName"`
	// Optional description of the environment
	Description *string `json:"description,omitempty"`
	// Optional reference to the dataplane. When omitted, the default dataplane is used.
	DataplaneRef *string `json:"dataplaneRef,omitempty"`
	// DNS prefix for the environment
	DnsPrefix string `json:"dnsPrefix"`
	// Whether this is a production environment
	IsProduction *bool        `json:"isProduction,omitempty"`
	Gateway      *GatewaySpec `json:"gateway,omitempty"`
}

// NewCreateEnvironmentRequest instantiates a new CreateEnvironmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEnvironmentRequest(name string, displayName string, dnsPrefix string) *CreateEnvironmentRequest {
	this := CreateEnvironmentRequest{}
	this.Name = name
	this.DisplayName = displayName
	this.DnsPrefix = dnsPrefix
	return &this
}

// NewCreateEnvironmentRequestWithDefaults instantiates a new CreateEnvironmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEnvironmentRequestWithDefaults() *CreateEnvironmentRequest {
	this := CreateEnvironmentRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateEnvironmentRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateEnvironmentRequest) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *CreateEnvironmentRequest) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *CreateEnvironmentRequest) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateEnvironmentRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateEnvironmentRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateEnvironmentRequest) SetDescription(v string) {
	o.Description = &v
}

// GetDataplaneRef returns the DataplaneRef field value if set, zero value otherwise.
func (o *CreateEnvironmentRequest) GetDataplaneRef() string {
	if o == nil || IsNil(o.DataplaneRef) {
		var ret string
		return ret
	}
	return *o.DataplaneRef
}

// GetDataplaneRefOk returns a tuple with the DataplaneRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentRequest) GetDataplaneRefOk() (*string, bool) {
	if o == nil || IsNil(o.DataplaneRef) {
		return nil, false
	}
	return o.DataplaneRef, true
}

// HasDataplaneRef returns a boolean if a field has been set.
func (o *CreateEnvironmentRequest) HasDataplaneRef() bool {
	if o != nil && !IsNil(o.DataplaneRef) {
		return true
	}

	return false
}

// SetDataplaneRef gets a reference to the given string and assigns it to the DataplaneRef field.
func (o *CreateEnvironmentRequest) SetDataplaneRef(v string) {
	o.DataplaneRef = &v
}

// GetDnsPrefix returns the DnsPrefix field value
func (o *CreateEnvironmentRequest) GetDnsPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DnsPrefix
}

// GetDnsPrefixOk returns a tuple with the DnsPrefix field value
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentRequest) GetDnsPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DnsPrefix, true
}

// SetDnsPrefix sets field value
func (o *CreateEnvironmentRequest) SetDnsPrefix(v string) {
	o.DnsPrefix = v
}

// GetIsProduction returns the IsProduction field value if set, zero value otherwise.
func (o *CreateEnvironmentRequest) GetIsProduction() bool {
	if o == nil || IsNil(o.IsProduction) {
		var ret bool
		return ret
	}
	return *o.IsProduction
}

// GetIsProductionOk returns a tuple with the IsProduction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentRequest) GetIsProductionOk() (*bool, bool) {
	if o == nil || IsNil(o.IsProduction) {
		return nil, false
	}
	return o.IsProduction, true
}

// HasIsProduction returns a boolean if a field has been set.
func (o *CreateEnvironmentRequest) HasIsProduction() bool {
	if o != nil && !IsNil(o.IsProduction) {
		return true
	}

	return false
}

// SetIsProduction gets a reference to the given bool and assigns it to the IsProduction field.
func (o *CreateEnvironmentRequest) SetIsProduction(v bool) {
	o.IsProduction = &v
}

// GetGateway returns the Gateway field value if set, zero value otherwise.
func (o *CreateEnvironmentRequest) GetGateway() GatewaySpec {
	if o == nil || IsNil(o.Gateway) {
		var ret GatewaySpec
		return ret
	}
	return *o.Gateway
}

// GetGatewayOk returns a tuple with the Gateway field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentRequest) GetGatewayOk() (*GatewaySpec, bool) {
	if o == nil || IsNil(o.Gateway) {
		return nil, false
	}
	return o.Gateway, true
}

// HasGateway returns a boolean if a field has been set.
func (o *CreateEnvironmentRequest) HasGateway() bool {
	if o != nil && !IsNil(o.Gateway) {
		return true
	}

	return false
}

// SetGateway gets a reference to the given GatewaySpec and assigns it to the Gateway field.
func (o *CreateEnvironmentRequest) SetGateway(v GatewaySpec) {
	o.Gateway = &v
}

func (o CreateEnvironmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEnvironmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DataplaneRef) {
		toSerialize["dataplaneRef"] = o.DataplaneRef
	}
	toSerialize["dnsPrefix"] = o.DnsPrefix
	if !IsNil(o.IsProduction) {
		toSerialize["isProduction"] = o.IsProduction
	}
	if !IsNil(o.Gateway) {
		toSerialize["gateway"] = o.Gateway
	}
	return toSerialize, nil
}

type NullableCreateEnvironmentRequest struct {
	value *CreateEnvironmentRequest
	isSet bool
}

func (v NullableCreateEnvironmentRequest) Get() *CreateEnvironmentRequest {
	return v.value
}

func (v *NullableCreateEnvironmentRequest) Set(val *CreateEnvironmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEnvironmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEnvironmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEnvironmentRequest(val *CreateEnvironmentRequest) *NullableCreateEnvironmentRequest {
	return &NullableCreateEnvironmentRequest{value: val, isSet: true}
}

func (v NullableCreateEnvironmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEnvironmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
