/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AddAgentKindVersionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddAgentKindVersionRequest{}

// AddAgentKindVersionRequest struct for AddAgentKindVersionRequest
type AddAgentKindVersionRequest struct {
	// Version tag for this release
	Version string `json:"version"`
	// Build name from the source agent's build history
	BuildName string `json:"buildName"`
	// Name of the agent the build belongs to
	SourceAgentName string `json:"sourceAgentName"`
	// Project the source agent belongs to
	SourceProjectName string `json:"sourceProjectName"`
	// Configuration schema for this version
	ConfigSchema []AgentKindConfigSchemaItem `json:"configSchema"`
	// Optional interface metadata (e.g. OpenAPI spec)
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// NewAddAgentKindVersionRequest instantiates a new AddAgentKindVersionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAgentKindVersionRequest(version string, buildName string, sourceAgentName string, sourceProjectName string, configSchema []AgentKindConfigSchemaItem) *AddAgentKindVersionRequest {
	this := AddAgentKindVersionRequest{}
	this.Version = version
	this.BuildName = buildName
	this.SourceAgentName = sourceAgentName
	this.SourceProjectName = sourceProjectName
	this.ConfigSchema = configSchema
	return &this
}

// NewAddAgentKindVersionRequestWithDefaults instantiates a new AddAgentKindVersionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAgentKindVersionRequestWithDefaults() *AddAgentKindVersionRequest {
	this := AddAgentKindVersionRequest{}
	return &this
}

// GetVersion returns the Version field value
func (o *AddAgentKindVersionRequest) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *AddAgentKindVersionRequest) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *AddAgentKindVersionRequest) SetVersion(v string) {
	o.Version = v
}

// GetBuildName returns the BuildName field value
func (o *AddAgentKindVersionRequest) GetBuildName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuildName
}

// GetBuildNameOk returns a tuple with the BuildName field value
// and a boolean to check if the value has been set.
func (o *AddAgentKindVersionRequest) GetBuildNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuildName, true
}

// SetBuildName sets field value
func (o *AddAgentKindVersionRequest) SetBuildName(v string) {
	o.BuildName = v
}

// GetSourceAgentName returns the SourceAgentName field value
func (o *AddAgentKindVersionRequest) GetSourceAgentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceAgentName
}

// GetSourceAgentNameOk returns a tuple with the SourceAgentName field value
// and a boolean to check if the value has been set.
func (o *AddAgentKindVersionRequest) GetSourceAgentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceAgentName, true
}

// SetSourceAgentName sets field value
func (o *AddAgentKindVersionRequest) SetSourceAgentName(v string) {
	o.SourceAgentName = v
}

// GetSourceProjectName returns the SourceProjectName field value
func (o *AddAgentKindVersionRequest) GetSourceProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceProjectName
}

// GetSourceProjectNameOk returns a tuple with the SourceProjectName field value
// and a boolean to check if the value has been set.
func (o *AddAgentKindVersionRequest) GetSourceProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceProjectName, true
}

// SetSourceProjectName sets field value
func (o *AddAgentKindVersionRequest) SetSourceProjectName(v string) {
	o.SourceProjectName = v
}

// GetConfigSchema returns the ConfigSchema field value
func (o *AddAgentKindVersionRequest) GetConfigSchema() []AgentKindConfigSchemaItem {
	if o == nil {
		var ret []AgentKindConfigSchemaItem
		return ret
	}

	return o.ConfigSchema
}

// GetConfigSchemaOk returns a tuple with the ConfigSchema field value
// and a boolean to check if the value has been set.
func (o *AddAgentKindVersionRequest) GetConfigSchemaOk() ([]AgentKindConfigSchemaItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfigSchema, true
}

// SetConfigSchema sets field value
func (o *AddAgentKindVersionRequest) SetConfigSchema(v []AgentKindConfigSchemaItem) {
	o.ConfigSchema = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddAgentKindVersionRequest) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddAgentKindVersionRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *AddAgentKindVersionRequest) HasMetadata() bool {
	if o != nil && IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *AddAgentKindVersionRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o AddAgentKindVersionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddAgentKindVersionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["buildName"] = o.BuildName
	toSerialize["sourceAgentName"] = o.SourceAgentName
	toSerialize["sourceProjectName"] = o.SourceProjectName
	toSerialize["configSchema"] = o.ConfigSchema
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableAddAgentKindVersionRequest struct {
	value *AddAgentKindVersionRequest
	isSet bool
}

func (v NullableAddAgentKindVersionRequest) Get() *AddAgentKindVersionRequest {
	return v.value
}

func (v *NullableAddAgentKindVersionRequest) Set(val *AddAgentKindVersionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAgentKindVersionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAgentKindVersionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAgentKindVersionRequest(val *AddAgentKindVersionRequest) *NullableAddAgentKindVersionRequest {
	return &NullableAddAgentKindVersionRequest{value: val, isSet: true}
}

func (v NullableAddAgentKindVersionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAgentKindVersionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
