/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the OidcDiscoveryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OidcDiscoveryResponse{}

// OidcDiscoveryResponse Issuer metadata resolved from an OpenID Connect discovery document, used to auto-populate the Add Identity Provider dialog.
type OidcDiscoveryResponse struct {
	// The `issuer` value from the discovery document.
	Issuer string `json:"issuer"`
	// The `jwks_uri` value from the discovery document.
	JwksUri string `json:"jwksUri"`
}

// NewOidcDiscoveryResponse instantiates a new OidcDiscoveryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOidcDiscoveryResponse(issuer string, jwksUri string) *OidcDiscoveryResponse {
	this := OidcDiscoveryResponse{}
	this.Issuer = issuer
	this.JwksUri = jwksUri
	return &this
}

// NewOidcDiscoveryResponseWithDefaults instantiates a new OidcDiscoveryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOidcDiscoveryResponseWithDefaults() *OidcDiscoveryResponse {
	this := OidcDiscoveryResponse{}
	return &this
}

// GetIssuer returns the Issuer field value
func (o *OidcDiscoveryResponse) GetIssuer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value
// and a boolean to check if the value has been set.
func (o *OidcDiscoveryResponse) GetIssuerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Issuer, true
}

// SetIssuer sets field value
func (o *OidcDiscoveryResponse) SetIssuer(v string) {
	o.Issuer = v
}

// GetJwksUri returns the JwksUri field value
func (o *OidcDiscoveryResponse) GetJwksUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JwksUri
}

// GetJwksUriOk returns a tuple with the JwksUri field value
// and a boolean to check if the value has been set.
func (o *OidcDiscoveryResponse) GetJwksUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JwksUri, true
}

// SetJwksUri sets field value
func (o *OidcDiscoveryResponse) SetJwksUri(v string) {
	o.JwksUri = v
}

func (o OidcDiscoveryResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OidcDiscoveryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["issuer"] = o.Issuer
	toSerialize["jwksUri"] = o.JwksUri
	return toSerialize, nil
}

type NullableOidcDiscoveryResponse struct {
	value *OidcDiscoveryResponse
	isSet bool
}

func (v NullableOidcDiscoveryResponse) Get() *OidcDiscoveryResponse {
	return v.value
}

func (v *NullableOidcDiscoveryResponse) Set(val *OidcDiscoveryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOidcDiscoveryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOidcDiscoveryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOidcDiscoveryResponse(val *OidcDiscoveryResponse) *NullableOidcDiscoveryResponse {
	return &NullableOidcDiscoveryResponse{value: val, isSet: true}
}

func (v NullableOidcDiscoveryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOidcDiscoveryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
