/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ThunderUrlResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThunderUrlResponse{}

// ThunderUrlResponse The env-Thunder registration for an environment. url is always present — the caller-supplied value (either path), or the value the server generated/computed when the caller left handle blank. handle is present only for the on-prem path; it is absent for an environment registered via a caller-supplied url.
type ThunderUrlResponse struct {
	Handle *string `json:"handle,omitempty"`
	Url    string  `json:"url"`
}

// NewThunderUrlResponse instantiates a new ThunderUrlResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThunderUrlResponse(url string) *ThunderUrlResponse {
	this := ThunderUrlResponse{}
	this.Url = url
	return &this
}

// NewThunderUrlResponseWithDefaults instantiates a new ThunderUrlResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThunderUrlResponseWithDefaults() *ThunderUrlResponse {
	this := ThunderUrlResponse{}
	return &this
}

// GetHandle returns the Handle field value if set, zero value otherwise.
func (o *ThunderUrlResponse) GetHandle() string {
	if o == nil || IsNil(o.Handle) {
		var ret string
		return ret
	}
	return *o.Handle
}

// GetHandleOk returns a tuple with the Handle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThunderUrlResponse) GetHandleOk() (*string, bool) {
	if o == nil || IsNil(o.Handle) {
		return nil, false
	}
	return o.Handle, true
}

// HasHandle returns a boolean if a field has been set.
func (o *ThunderUrlResponse) HasHandle() bool {
	if o != nil && !IsNil(o.Handle) {
		return true
	}

	return false
}

// SetHandle gets a reference to the given string and assigns it to the Handle field.
func (o *ThunderUrlResponse) SetHandle(v string) {
	o.Handle = &v
}

// GetUrl returns the Url field value
func (o *ThunderUrlResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ThunderUrlResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ThunderUrlResponse) SetUrl(v string) {
	o.Url = v
}

func (o ThunderUrlResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThunderUrlResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Handle) {
		toSerialize["handle"] = o.Handle
	}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

type NullableThunderUrlResponse struct {
	value *ThunderUrlResponse
	isSet bool
}

func (v NullableThunderUrlResponse) Get() *ThunderUrlResponse {
	return v.value
}

func (v *NullableThunderUrlResponse) Set(val *ThunderUrlResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableThunderUrlResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableThunderUrlResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThunderUrlResponse(val *ThunderUrlResponse) *NullableThunderUrlResponse {
	return &NullableThunderUrlResponse{value: val, isSet: true}
}

func (v NullableThunderUrlResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThunderUrlResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
