/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the ListCommitsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCommitsRequest{}

// ListCommitsRequest Request body for listing repository commits
type ListCommitsRequest struct {
	// Repository owner (organization or user)
	Owner string `json:"owner"`
	// Repository name
	Repo string `json:"repo"`
	// Branch name or SHA to list commits from (defaults to repository's default branch)
	Branch *string `json:"branch,omitempty"`
	// Filter commits affecting this file path
	Path *string `json:"path,omitempty"`
	// Filter commits by author (GitHub username or email)
	Author *string `json:"author,omitempty"`
	// Filter commits after this date (RFC3339 format)
	Since *time.Time `json:"since,omitempty"`
	// Filter commits before this date (RFC3339 format)
	Until *time.Time `json:"until,omitempty"`
	// Secret reference name for private repository Git credentials
	SecretRef *string `json:"secretRef,omitempty"`
	// Optional project name used to resolve a deployment-specific repository binding
	ProjectName *string `json:"projectName,omitempty"`
	// Optional component name used to resolve a deployment-specific repository binding
	ComponentName *string `json:"componentName,omitempty"`
}

// NewListCommitsRequest instantiates a new ListCommitsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCommitsRequest(owner string, repo string) *ListCommitsRequest {
	this := ListCommitsRequest{}
	this.Owner = owner
	this.Repo = repo
	return &this
}

// NewListCommitsRequestWithDefaults instantiates a new ListCommitsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCommitsRequestWithDefaults() *ListCommitsRequest {
	this := ListCommitsRequest{}
	return &this
}

// GetOwner returns the Owner field value
func (o *ListCommitsRequest) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *ListCommitsRequest) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *ListCommitsRequest) SetOwner(v string) {
	o.Owner = v
}

// GetRepo returns the Repo field value
func (o *ListCommitsRequest) GetRepo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Repo
}

// GetRepoOk returns a tuple with the Repo field value
// and a boolean to check if the value has been set.
func (o *ListCommitsRequest) GetRepoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Repo, true
}

// SetRepo sets field value
func (o *ListCommitsRequest) SetRepo(v string) {
	o.Repo = v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *ListCommitsRequest) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCommitsRequest) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *ListCommitsRequest) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *ListCommitsRequest) SetBranch(v string) {
	o.Branch = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ListCommitsRequest) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCommitsRequest) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ListCommitsRequest) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ListCommitsRequest) SetPath(v string) {
	o.Path = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *ListCommitsRequest) GetAuthor() string {
	if o == nil || IsNil(o.Author) {
		var ret string
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCommitsRequest) GetAuthorOk() (*string, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *ListCommitsRequest) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given string and assigns it to the Author field.
func (o *ListCommitsRequest) SetAuthor(v string) {
	o.Author = &v
}

// GetSince returns the Since field value if set, zero value otherwise.
func (o *ListCommitsRequest) GetSince() time.Time {
	if o == nil || IsNil(o.Since) {
		var ret time.Time
		return ret
	}
	return *o.Since
}

// GetSinceOk returns a tuple with the Since field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCommitsRequest) GetSinceOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Since) {
		return nil, false
	}
	return o.Since, true
}

// HasSince returns a boolean if a field has been set.
func (o *ListCommitsRequest) HasSince() bool {
	if o != nil && !IsNil(o.Since) {
		return true
	}

	return false
}

// SetSince gets a reference to the given time.Time and assigns it to the Since field.
func (o *ListCommitsRequest) SetSince(v time.Time) {
	o.Since = &v
}

// GetUntil returns the Until field value if set, zero value otherwise.
func (o *ListCommitsRequest) GetUntil() time.Time {
	if o == nil || IsNil(o.Until) {
		var ret time.Time
		return ret
	}
	return *o.Until
}

// GetUntilOk returns a tuple with the Until field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCommitsRequest) GetUntilOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Until) {
		return nil, false
	}
	return o.Until, true
}

// HasUntil returns a boolean if a field has been set.
func (o *ListCommitsRequest) HasUntil() bool {
	if o != nil && !IsNil(o.Until) {
		return true
	}

	return false
}

// SetUntil gets a reference to the given time.Time and assigns it to the Until field.
func (o *ListCommitsRequest) SetUntil(v time.Time) {
	o.Until = &v
}

// GetSecretRef returns the SecretRef field value if set, zero value otherwise.
func (o *ListCommitsRequest) GetSecretRef() string {
	if o == nil || IsNil(o.SecretRef) {
		var ret string
		return ret
	}
	return *o.SecretRef
}

// GetSecretRefOk returns a tuple with the SecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCommitsRequest) GetSecretRefOk() (*string, bool) {
	if o == nil || IsNil(o.SecretRef) {
		return nil, false
	}
	return o.SecretRef, true
}

// HasSecretRef returns a boolean if a field has been set.
func (o *ListCommitsRequest) HasSecretRef() bool {
	if o != nil && !IsNil(o.SecretRef) {
		return true
	}

	return false
}

// SetSecretRef gets a reference to the given string and assigns it to the SecretRef field.
func (o *ListCommitsRequest) SetSecretRef(v string) {
	o.SecretRef = &v
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *ListCommitsRequest) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName) {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCommitsRequest) GetProjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectName) {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *ListCommitsRequest) HasProjectName() bool {
	if o != nil && !IsNil(o.ProjectName) {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *ListCommitsRequest) SetProjectName(v string) {
	o.ProjectName = &v
}

// GetComponentName returns the ComponentName field value if set, zero value otherwise.
func (o *ListCommitsRequest) GetComponentName() string {
	if o == nil || IsNil(o.ComponentName) {
		var ret string
		return ret
	}
	return *o.ComponentName
}

// GetComponentNameOk returns a tuple with the ComponentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCommitsRequest) GetComponentNameOk() (*string, bool) {
	if o == nil || IsNil(o.ComponentName) {
		return nil, false
	}
	return o.ComponentName, true
}

// HasComponentName returns a boolean if a field has been set.
func (o *ListCommitsRequest) HasComponentName() bool {
	if o != nil && !IsNil(o.ComponentName) {
		return true
	}

	return false
}

// SetComponentName gets a reference to the given string and assigns it to the ComponentName field.
func (o *ListCommitsRequest) SetComponentName(v string) {
	o.ComponentName = &v
}

func (o ListCommitsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCommitsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["owner"] = o.Owner
	toSerialize["repo"] = o.Repo
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.Since) {
		toSerialize["since"] = o.Since
	}
	if !IsNil(o.Until) {
		toSerialize["until"] = o.Until
	}
	if !IsNil(o.SecretRef) {
		toSerialize["secretRef"] = o.SecretRef
	}
	if !IsNil(o.ProjectName) {
		toSerialize["projectName"] = o.ProjectName
	}
	if !IsNil(o.ComponentName) {
		toSerialize["componentName"] = o.ComponentName
	}
	return toSerialize, nil
}

type NullableListCommitsRequest struct {
	value *ListCommitsRequest
	isSet bool
}

func (v NullableListCommitsRequest) Get() *ListCommitsRequest {
	return v.value
}

func (v *NullableListCommitsRequest) Set(val *ListCommitsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListCommitsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListCommitsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCommitsRequest(val *ListCommitsRequest) *NullableListCommitsRequest {
	return &NullableListCommitsRequest{value: val, isSet: true}
}

func (v NullableListCommitsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCommitsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
