/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the PromoteAgentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromoteAgentRequest{}

// PromoteAgentRequest struct for PromoteAgentRequest
type PromoteAgentRequest struct {
	// Source environment to promote from
	SourceEnvironment string `json:"sourceEnvironment"`
	// Target environment to promote to
	TargetEnvironment string `json:"targetEnvironment"`
	// When true, the target environment inherits BOTH its configurations AND its deploy settings from the source environment.  mode — they are mutually exclusive with useConfigFromSourceEnv=true. When false or omitted, the per-environment overrides must be supplied in the request.
	UseConfigFromSourceEnv *bool `json:"useConfigFromSourceEnv,omitempty"`
	// Environment-specific environment variables for the target environment.
	Env []EnvironmentVariable `json:"env,omitempty"`
	// Environment-specific file mounts for the target environment.
	Files []FileMount `json:"files,omitempty"`
	// Enable auto instrumentation for observability in the target environment
	EnableAutoInstrumentation *bool `json:"enableAutoInstrumentation,omitempty"`
	// Enable API key security for the agent endpoint in the target environment
	EnableApiKeySecurity *bool       `json:"enableApiKeySecurity,omitempty"`
	CorsConfig           *CORSConfig `json:"corsConfig,omitempty"`
	// Enable OAuth security for the agent endpoint in the target environment. Mutually exclusive with enableApiKeySecurity.
	EnableOAuthSecurity *bool        `json:"enableOAuthSecurity,omitempty"`
	OauthConfig         *OAuthConfig `json:"oauthConfig,omitempty"`
}

// NewPromoteAgentRequest instantiates a new PromoteAgentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromoteAgentRequest(sourceEnvironment string, targetEnvironment string) *PromoteAgentRequest {
	this := PromoteAgentRequest{}
	this.SourceEnvironment = sourceEnvironment
	this.TargetEnvironment = targetEnvironment
	return &this
}

// NewPromoteAgentRequestWithDefaults instantiates a new PromoteAgentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromoteAgentRequestWithDefaults() *PromoteAgentRequest {
	this := PromoteAgentRequest{}
	return &this
}

// GetSourceEnvironment returns the SourceEnvironment field value
func (o *PromoteAgentRequest) GetSourceEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceEnvironment
}

// GetSourceEnvironmentOk returns a tuple with the SourceEnvironment field value
// and a boolean to check if the value has been set.
func (o *PromoteAgentRequest) GetSourceEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceEnvironment, true
}

// SetSourceEnvironment sets field value
func (o *PromoteAgentRequest) SetSourceEnvironment(v string) {
	o.SourceEnvironment = v
}

// GetTargetEnvironment returns the TargetEnvironment field value
func (o *PromoteAgentRequest) GetTargetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetEnvironment
}

// GetTargetEnvironmentOk returns a tuple with the TargetEnvironment field value
// and a boolean to check if the value has been set.
func (o *PromoteAgentRequest) GetTargetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetEnvironment, true
}

// SetTargetEnvironment sets field value
func (o *PromoteAgentRequest) SetTargetEnvironment(v string) {
	o.TargetEnvironment = v
}

// GetUseConfigFromSourceEnv returns the UseConfigFromSourceEnv field value if set, zero value otherwise.
func (o *PromoteAgentRequest) GetUseConfigFromSourceEnv() bool {
	if o == nil || IsNil(o.UseConfigFromSourceEnv) {
		var ret bool
		return ret
	}
	return *o.UseConfigFromSourceEnv
}

// GetUseConfigFromSourceEnvOk returns a tuple with the UseConfigFromSourceEnv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteAgentRequest) GetUseConfigFromSourceEnvOk() (*bool, bool) {
	if o == nil || IsNil(o.UseConfigFromSourceEnv) {
		return nil, false
	}
	return o.UseConfigFromSourceEnv, true
}

// HasUseConfigFromSourceEnv returns a boolean if a field has been set.
func (o *PromoteAgentRequest) HasUseConfigFromSourceEnv() bool {
	if o != nil && !IsNil(o.UseConfigFromSourceEnv) {
		return true
	}

	return false
}

// SetUseConfigFromSourceEnv gets a reference to the given bool and assigns it to the UseConfigFromSourceEnv field.
func (o *PromoteAgentRequest) SetUseConfigFromSourceEnv(v bool) {
	o.UseConfigFromSourceEnv = &v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *PromoteAgentRequest) GetEnv() []EnvironmentVariable {
	if o == nil || IsNil(o.Env) {
		var ret []EnvironmentVariable
		return ret
	}
	return o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteAgentRequest) GetEnvOk() ([]EnvironmentVariable, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *PromoteAgentRequest) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given []EnvironmentVariable and assigns it to the Env field.
func (o *PromoteAgentRequest) SetEnv(v []EnvironmentVariable) {
	o.Env = v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *PromoteAgentRequest) GetFiles() []FileMount {
	if o == nil || IsNil(o.Files) {
		var ret []FileMount
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteAgentRequest) GetFilesOk() ([]FileMount, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *PromoteAgentRequest) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []FileMount and assigns it to the Files field.
func (o *PromoteAgentRequest) SetFiles(v []FileMount) {
	o.Files = v
}

// GetEnableAutoInstrumentation returns the EnableAutoInstrumentation field value if set, zero value otherwise.
func (o *PromoteAgentRequest) GetEnableAutoInstrumentation() bool {
	if o == nil || IsNil(o.EnableAutoInstrumentation) {
		var ret bool
		return ret
	}
	return *o.EnableAutoInstrumentation
}

// GetEnableAutoInstrumentationOk returns a tuple with the EnableAutoInstrumentation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteAgentRequest) GetEnableAutoInstrumentationOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableAutoInstrumentation) {
		return nil, false
	}
	return o.EnableAutoInstrumentation, true
}

// HasEnableAutoInstrumentation returns a boolean if a field has been set.
func (o *PromoteAgentRequest) HasEnableAutoInstrumentation() bool {
	if o != nil && !IsNil(o.EnableAutoInstrumentation) {
		return true
	}

	return false
}

// SetEnableAutoInstrumentation gets a reference to the given bool and assigns it to the EnableAutoInstrumentation field.
func (o *PromoteAgentRequest) SetEnableAutoInstrumentation(v bool) {
	o.EnableAutoInstrumentation = &v
}

// GetEnableApiKeySecurity returns the EnableApiKeySecurity field value if set, zero value otherwise.
func (o *PromoteAgentRequest) GetEnableApiKeySecurity() bool {
	if o == nil || IsNil(o.EnableApiKeySecurity) {
		var ret bool
		return ret
	}
	return *o.EnableApiKeySecurity
}

// GetEnableApiKeySecurityOk returns a tuple with the EnableApiKeySecurity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteAgentRequest) GetEnableApiKeySecurityOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableApiKeySecurity) {
		return nil, false
	}
	return o.EnableApiKeySecurity, true
}

// HasEnableApiKeySecurity returns a boolean if a field has been set.
func (o *PromoteAgentRequest) HasEnableApiKeySecurity() bool {
	if o != nil && !IsNil(o.EnableApiKeySecurity) {
		return true
	}

	return false
}

// SetEnableApiKeySecurity gets a reference to the given bool and assigns it to the EnableApiKeySecurity field.
func (o *PromoteAgentRequest) SetEnableApiKeySecurity(v bool) {
	o.EnableApiKeySecurity = &v
}

// GetCorsConfig returns the CorsConfig field value if set, zero value otherwise.
func (o *PromoteAgentRequest) GetCorsConfig() CORSConfig {
	if o == nil || IsNil(o.CorsConfig) {
		var ret CORSConfig
		return ret
	}
	return *o.CorsConfig
}

// GetCorsConfigOk returns a tuple with the CorsConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteAgentRequest) GetCorsConfigOk() (*CORSConfig, bool) {
	if o == nil || IsNil(o.CorsConfig) {
		return nil, false
	}
	return o.CorsConfig, true
}

// HasCorsConfig returns a boolean if a field has been set.
func (o *PromoteAgentRequest) HasCorsConfig() bool {
	if o != nil && !IsNil(o.CorsConfig) {
		return true
	}

	return false
}

// SetCorsConfig gets a reference to the given CORSConfig and assigns it to the CorsConfig field.
func (o *PromoteAgentRequest) SetCorsConfig(v CORSConfig) {
	o.CorsConfig = &v
}

// GetEnableOAuthSecurity returns the EnableOAuthSecurity field value if set, zero value otherwise.
func (o *PromoteAgentRequest) GetEnableOAuthSecurity() bool {
	if o == nil || IsNil(o.EnableOAuthSecurity) {
		var ret bool
		return ret
	}
	return *o.EnableOAuthSecurity
}

// GetEnableOAuthSecurityOk returns a tuple with the EnableOAuthSecurity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteAgentRequest) GetEnableOAuthSecurityOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableOAuthSecurity) {
		return nil, false
	}
	return o.EnableOAuthSecurity, true
}

// HasEnableOAuthSecurity returns a boolean if a field has been set.
func (o *PromoteAgentRequest) HasEnableOAuthSecurity() bool {
	if o != nil && !IsNil(o.EnableOAuthSecurity) {
		return true
	}

	return false
}

// SetEnableOAuthSecurity gets a reference to the given bool and assigns it to the EnableOAuthSecurity field.
func (o *PromoteAgentRequest) SetEnableOAuthSecurity(v bool) {
	o.EnableOAuthSecurity = &v
}

// GetOauthConfig returns the OauthConfig field value if set, zero value otherwise.
func (o *PromoteAgentRequest) GetOauthConfig() OAuthConfig {
	if o == nil || IsNil(o.OauthConfig) {
		var ret OAuthConfig
		return ret
	}
	return *o.OauthConfig
}

// GetOauthConfigOk returns a tuple with the OauthConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteAgentRequest) GetOauthConfigOk() (*OAuthConfig, bool) {
	if o == nil || IsNil(o.OauthConfig) {
		return nil, false
	}
	return o.OauthConfig, true
}

// HasOauthConfig returns a boolean if a field has been set.
func (o *PromoteAgentRequest) HasOauthConfig() bool {
	if o != nil && !IsNil(o.OauthConfig) {
		return true
	}

	return false
}

// SetOauthConfig gets a reference to the given OAuthConfig and assigns it to the OauthConfig field.
func (o *PromoteAgentRequest) SetOauthConfig(v OAuthConfig) {
	o.OauthConfig = &v
}

func (o PromoteAgentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromoteAgentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sourceEnvironment"] = o.SourceEnvironment
	toSerialize["targetEnvironment"] = o.TargetEnvironment
	if !IsNil(o.UseConfigFromSourceEnv) {
		toSerialize["useConfigFromSourceEnv"] = o.UseConfigFromSourceEnv
	}
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	if !IsNil(o.EnableAutoInstrumentation) {
		toSerialize["enableAutoInstrumentation"] = o.EnableAutoInstrumentation
	}
	if !IsNil(o.EnableApiKeySecurity) {
		toSerialize["enableApiKeySecurity"] = o.EnableApiKeySecurity
	}
	if !IsNil(o.CorsConfig) {
		toSerialize["corsConfig"] = o.CorsConfig
	}
	if !IsNil(o.EnableOAuthSecurity) {
		toSerialize["enableOAuthSecurity"] = o.EnableOAuthSecurity
	}
	if !IsNil(o.OauthConfig) {
		toSerialize["oauthConfig"] = o.OauthConfig
	}
	return toSerialize, nil
}

type NullablePromoteAgentRequest struct {
	value *PromoteAgentRequest
	isSet bool
}

func (v NullablePromoteAgentRequest) Get() *PromoteAgentRequest {
	return v.value
}

func (v *NullablePromoteAgentRequest) Set(val *PromoteAgentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePromoteAgentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePromoteAgentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromoteAgentRequest(val *PromoteAgentRequest) *NullablePromoteAgentRequest {
	return &NullablePromoteAgentRequest{value: val, isSet: true}
}

func (v NullablePromoteAgentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromoteAgentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
