/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the Configurations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Configurations{}

// Configurations struct for Configurations
type Configurations struct {
	// Environment variables
	Env []EnvironmentVariable `json:"env,omitempty"`
	// File mounts
	Files []FileMount `json:"files,omitempty"`
	// Enable automatic OTEL instrumentation for the agent
	EnableAutoInstrumentation *bool `json:"enableAutoInstrumentation,omitempty"`
	// AMP instrumentation version to use for the agent. Selects the pre-built init-container image (`amp-python-instrumentation-provider:<version>-python<X.Y>`) and the `traceloop-sdk` it pins. Omit (or send null) to use the platform default. Must be one of the versions supported by the deployment; unknown values are rejected.
	InstrumentationVersion NullableString `json:"instrumentationVersion,omitempty"`
	// Enable API key security for the agent endpoint
	EnableApiKeySecurity *bool       `json:"enableApiKeySecurity,omitempty"`
	CorsConfig           *CORSConfig `json:"corsConfig,omitempty"`
	// Enable OAuth security for the agent endpoint. Mutually exclusive with enableApiKeySecurity.
	EnableOAuthSecurity *bool        `json:"enableOAuthSecurity,omitempty"`
	OauthConfig         *OAuthConfig `json:"oauthConfig,omitempty"`
}

// NewConfigurations instantiates a new Configurations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurations() *Configurations {
	this := Configurations{}
	var enableAutoInstrumentation bool = true
	this.EnableAutoInstrumentation = &enableAutoInstrumentation
	var enableApiKeySecurity bool = true
	this.EnableApiKeySecurity = &enableApiKeySecurity
	var enableOAuthSecurity bool = false
	this.EnableOAuthSecurity = &enableOAuthSecurity
	return &this
}

// NewConfigurationsWithDefaults instantiates a new Configurations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationsWithDefaults() *Configurations {
	this := Configurations{}
	var enableAutoInstrumentation bool = true
	this.EnableAutoInstrumentation = &enableAutoInstrumentation
	var enableApiKeySecurity bool = true
	this.EnableApiKeySecurity = &enableApiKeySecurity
	var enableOAuthSecurity bool = false
	this.EnableOAuthSecurity = &enableOAuthSecurity
	return &this
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *Configurations) GetEnv() []EnvironmentVariable {
	if o == nil || IsNil(o.Env) {
		var ret []EnvironmentVariable
		return ret
	}
	return o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configurations) GetEnvOk() ([]EnvironmentVariable, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *Configurations) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given []EnvironmentVariable and assigns it to the Env field.
func (o *Configurations) SetEnv(v []EnvironmentVariable) {
	o.Env = v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *Configurations) GetFiles() []FileMount {
	if o == nil || IsNil(o.Files) {
		var ret []FileMount
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configurations) GetFilesOk() ([]FileMount, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *Configurations) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []FileMount and assigns it to the Files field.
func (o *Configurations) SetFiles(v []FileMount) {
	o.Files = v
}

// GetEnableAutoInstrumentation returns the EnableAutoInstrumentation field value if set, zero value otherwise.
func (o *Configurations) GetEnableAutoInstrumentation() bool {
	if o == nil || IsNil(o.EnableAutoInstrumentation) {
		var ret bool
		return ret
	}
	return *o.EnableAutoInstrumentation
}

// GetEnableAutoInstrumentationOk returns a tuple with the EnableAutoInstrumentation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configurations) GetEnableAutoInstrumentationOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableAutoInstrumentation) {
		return nil, false
	}
	return o.EnableAutoInstrumentation, true
}

// HasEnableAutoInstrumentation returns a boolean if a field has been set.
func (o *Configurations) HasEnableAutoInstrumentation() bool {
	if o != nil && !IsNil(o.EnableAutoInstrumentation) {
		return true
	}

	return false
}

// SetEnableAutoInstrumentation gets a reference to the given bool and assigns it to the EnableAutoInstrumentation field.
func (o *Configurations) SetEnableAutoInstrumentation(v bool) {
	o.EnableAutoInstrumentation = &v
}

// GetInstrumentationVersion returns the InstrumentationVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Configurations) GetInstrumentationVersion() string {
	if o == nil || IsNil(o.InstrumentationVersion.Get()) {
		var ret string
		return ret
	}
	return *o.InstrumentationVersion.Get()
}

// GetInstrumentationVersionOk returns a tuple with the InstrumentationVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Configurations) GetInstrumentationVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InstrumentationVersion.Get(), o.InstrumentationVersion.IsSet()
}

// HasInstrumentationVersion returns a boolean if a field has been set.
func (o *Configurations) HasInstrumentationVersion() bool {
	if o != nil && o.InstrumentationVersion.IsSet() {
		return true
	}

	return false
}

// SetInstrumentationVersion gets a reference to the given NullableString and assigns it to the InstrumentationVersion field.
func (o *Configurations) SetInstrumentationVersion(v string) {
	o.InstrumentationVersion.Set(&v)
}

// SetInstrumentationVersionNil sets the value for InstrumentationVersion to be an explicit nil
func (o *Configurations) SetInstrumentationVersionNil() {
	o.InstrumentationVersion.Set(nil)
}

// UnsetInstrumentationVersion ensures that no value is present for InstrumentationVersion, not even an explicit nil
func (o *Configurations) UnsetInstrumentationVersion() {
	o.InstrumentationVersion.Unset()
}

// GetEnableApiKeySecurity returns the EnableApiKeySecurity field value if set, zero value otherwise.
func (o *Configurations) GetEnableApiKeySecurity() bool {
	if o == nil || IsNil(o.EnableApiKeySecurity) {
		var ret bool
		return ret
	}
	return *o.EnableApiKeySecurity
}

// GetEnableApiKeySecurityOk returns a tuple with the EnableApiKeySecurity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configurations) GetEnableApiKeySecurityOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableApiKeySecurity) {
		return nil, false
	}
	return o.EnableApiKeySecurity, true
}

// HasEnableApiKeySecurity returns a boolean if a field has been set.
func (o *Configurations) HasEnableApiKeySecurity() bool {
	if o != nil && !IsNil(o.EnableApiKeySecurity) {
		return true
	}

	return false
}

// SetEnableApiKeySecurity gets a reference to the given bool and assigns it to the EnableApiKeySecurity field.
func (o *Configurations) SetEnableApiKeySecurity(v bool) {
	o.EnableApiKeySecurity = &v
}

// GetCorsConfig returns the CorsConfig field value if set, zero value otherwise.
func (o *Configurations) GetCorsConfig() CORSConfig {
	if o == nil || IsNil(o.CorsConfig) {
		var ret CORSConfig
		return ret
	}
	return *o.CorsConfig
}

// GetCorsConfigOk returns a tuple with the CorsConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configurations) GetCorsConfigOk() (*CORSConfig, bool) {
	if o == nil || IsNil(o.CorsConfig) {
		return nil, false
	}
	return o.CorsConfig, true
}

// HasCorsConfig returns a boolean if a field has been set.
func (o *Configurations) HasCorsConfig() bool {
	if o != nil && !IsNil(o.CorsConfig) {
		return true
	}

	return false
}

// SetCorsConfig gets a reference to the given CORSConfig and assigns it to the CorsConfig field.
func (o *Configurations) SetCorsConfig(v CORSConfig) {
	o.CorsConfig = &v
}

// GetEnableOAuthSecurity returns the EnableOAuthSecurity field value if set, zero value otherwise.
func (o *Configurations) GetEnableOAuthSecurity() bool {
	if o == nil || IsNil(o.EnableOAuthSecurity) {
		var ret bool
		return ret
	}
	return *o.EnableOAuthSecurity
}

// GetEnableOAuthSecurityOk returns a tuple with the EnableOAuthSecurity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configurations) GetEnableOAuthSecurityOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableOAuthSecurity) {
		return nil, false
	}
	return o.EnableOAuthSecurity, true
}

// HasEnableOAuthSecurity returns a boolean if a field has been set.
func (o *Configurations) HasEnableOAuthSecurity() bool {
	if o != nil && !IsNil(o.EnableOAuthSecurity) {
		return true
	}

	return false
}

// SetEnableOAuthSecurity gets a reference to the given bool and assigns it to the EnableOAuthSecurity field.
func (o *Configurations) SetEnableOAuthSecurity(v bool) {
	o.EnableOAuthSecurity = &v
}

// GetOauthConfig returns the OauthConfig field value if set, zero value otherwise.
func (o *Configurations) GetOauthConfig() OAuthConfig {
	if o == nil || IsNil(o.OauthConfig) {
		var ret OAuthConfig
		return ret
	}
	return *o.OauthConfig
}

// GetOauthConfigOk returns a tuple with the OauthConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configurations) GetOauthConfigOk() (*OAuthConfig, bool) {
	if o == nil || IsNil(o.OauthConfig) {
		return nil, false
	}
	return o.OauthConfig, true
}

// HasOauthConfig returns a boolean if a field has been set.
func (o *Configurations) HasOauthConfig() bool {
	if o != nil && !IsNil(o.OauthConfig) {
		return true
	}

	return false
}

// SetOauthConfig gets a reference to the given OAuthConfig and assigns it to the OauthConfig field.
func (o *Configurations) SetOauthConfig(v OAuthConfig) {
	o.OauthConfig = &v
}

func (o Configurations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Configurations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	if !IsNil(o.EnableAutoInstrumentation) {
		toSerialize["enableAutoInstrumentation"] = o.EnableAutoInstrumentation
	}
	if o.InstrumentationVersion.IsSet() {
		toSerialize["instrumentationVersion"] = o.InstrumentationVersion.Get()
	}
	if !IsNil(o.EnableApiKeySecurity) {
		toSerialize["enableApiKeySecurity"] = o.EnableApiKeySecurity
	}
	if !IsNil(o.CorsConfig) {
		toSerialize["corsConfig"] = o.CorsConfig
	}
	if !IsNil(o.EnableOAuthSecurity) {
		toSerialize["enableOAuthSecurity"] = o.EnableOAuthSecurity
	}
	if !IsNil(o.OauthConfig) {
		toSerialize["oauthConfig"] = o.OauthConfig
	}
	return toSerialize, nil
}

type NullableConfigurations struct {
	value *Configurations
	isSet bool
}

func (v NullableConfigurations) Get() *Configurations {
	return v.value
}

func (v *NullableConfigurations) Set(val *Configurations) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurations) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurations(val *Configurations) *NullableConfigurations {
	return &NullableConfigurations{value: val, isSet: true}
}

func (v NullableConfigurations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
