/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ConfigResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigResponse{}

// ConfigResponse struct for ConfigResponse
type ConfigResponse struct {
	// Base URL for the traces observer service
	TraceObserverBaseUrl string `json:"traceObserverBaseUrl"`
}

// NewConfigResponse instantiates a new ConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigResponse(traceObserverBaseUrl string) *ConfigResponse {
	this := ConfigResponse{}
	this.TraceObserverBaseUrl = traceObserverBaseUrl
	return &this
}

// NewConfigResponseWithDefaults instantiates a new ConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigResponseWithDefaults() *ConfigResponse {
	this := ConfigResponse{}
	return &this
}

// GetTraceObserverBaseUrl returns the TraceObserverBaseUrl field value
func (o *ConfigResponse) GetTraceObserverBaseUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TraceObserverBaseUrl
}

// GetTraceObserverBaseUrlOk returns a tuple with the TraceObserverBaseUrl field value
// and a boolean to check if the value has been set.
func (o *ConfigResponse) GetTraceObserverBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TraceObserverBaseUrl, true
}

// SetTraceObserverBaseUrl sets field value
func (o *ConfigResponse) SetTraceObserverBaseUrl(v string) {
	o.TraceObserverBaseUrl = v
}

func (o ConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["traceObserverBaseUrl"] = o.TraceObserverBaseUrl
	return toSerialize, nil
}

type NullableConfigResponse struct {
	value *ConfigResponse
	isSet bool
}

func (v NullableConfigResponse) Get() *ConfigResponse {
	return v.value
}

func (v *NullableConfigResponse) Set(val *ConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigResponse(val *ConfigResponse) *NullableConfigResponse {
	return &NullableConfigResponse{value: val, isSet: true}
}

func (v NullableConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
