/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the OAuthConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuthConfig{}

// OAuthConfig OAuth security configuration for the agent endpoint. Callers authenticate with a standard Authorization Bearer token validated by the gateway.
type OAuthConfig struct {
	// Issuer names for token validation, referencing identity provider entries configured gateway-side. Must be non-empty when OAuth security is enabled, and every name must be one of the environment's configured identity providers.
	Issuers []string `json:"issuers,omitempty"`
	// Accepted token audiences (aud claim). Validation succeeds only when at least one configured audience is present in the token. Empty disables audience validation.
	Audiences []string `json:"audiences,omitempty"`
	// Request header carrying the token.
	HeaderName *string `json:"headerName,omitempty"`
	// Prefix before the token in the header value.
	AuthHeaderPrefix *string `json:"authHeaderPrefix,omitempty"`
	// When true, the original token header is forwarded to the upstream service after successful validation. When false, it is stripped before the request is proxied.
	ForwardToken *bool `json:"forwardToken,omitempty"`
}

// NewOAuthConfig instantiates a new OAuthConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuthConfig() *OAuthConfig {
	this := OAuthConfig{}
	var headerName string = "Authorization"
	this.HeaderName = &headerName
	var authHeaderPrefix string = "Bearer"
	this.AuthHeaderPrefix = &authHeaderPrefix
	var forwardToken bool = true
	this.ForwardToken = &forwardToken
	return &this
}

// NewOAuthConfigWithDefaults instantiates a new OAuthConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuthConfigWithDefaults() *OAuthConfig {
	this := OAuthConfig{}
	var headerName string = "Authorization"
	this.HeaderName = &headerName
	var authHeaderPrefix string = "Bearer"
	this.AuthHeaderPrefix = &authHeaderPrefix
	var forwardToken bool = true
	this.ForwardToken = &forwardToken
	return &this
}

// GetIssuers returns the Issuers field value if set, zero value otherwise.
func (o *OAuthConfig) GetIssuers() []string {
	if o == nil || IsNil(o.Issuers) {
		var ret []string
		return ret
	}
	return o.Issuers
}

// GetIssuersOk returns a tuple with the Issuers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthConfig) GetIssuersOk() ([]string, bool) {
	if o == nil || IsNil(o.Issuers) {
		return nil, false
	}
	return o.Issuers, true
}

// HasIssuers returns a boolean if a field has been set.
func (o *OAuthConfig) HasIssuers() bool {
	if o != nil && !IsNil(o.Issuers) {
		return true
	}

	return false
}

// SetIssuers gets a reference to the given []string and assigns it to the Issuers field.
func (o *OAuthConfig) SetIssuers(v []string) {
	o.Issuers = v
}

// GetAudiences returns the Audiences field value if set, zero value otherwise.
func (o *OAuthConfig) GetAudiences() []string {
	if o == nil || IsNil(o.Audiences) {
		var ret []string
		return ret
	}
	return o.Audiences
}

// GetAudiencesOk returns a tuple with the Audiences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthConfig) GetAudiencesOk() ([]string, bool) {
	if o == nil || IsNil(o.Audiences) {
		return nil, false
	}
	return o.Audiences, true
}

// HasAudiences returns a boolean if a field has been set.
func (o *OAuthConfig) HasAudiences() bool {
	if o != nil && !IsNil(o.Audiences) {
		return true
	}

	return false
}

// SetAudiences gets a reference to the given []string and assigns it to the Audiences field.
func (o *OAuthConfig) SetAudiences(v []string) {
	o.Audiences = v
}

// GetHeaderName returns the HeaderName field value if set, zero value otherwise.
func (o *OAuthConfig) GetHeaderName() string {
	if o == nil || IsNil(o.HeaderName) {
		var ret string
		return ret
	}
	return *o.HeaderName
}

// GetHeaderNameOk returns a tuple with the HeaderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthConfig) GetHeaderNameOk() (*string, bool) {
	if o == nil || IsNil(o.HeaderName) {
		return nil, false
	}
	return o.HeaderName, true
}

// HasHeaderName returns a boolean if a field has been set.
func (o *OAuthConfig) HasHeaderName() bool {
	if o != nil && !IsNil(o.HeaderName) {
		return true
	}

	return false
}

// SetHeaderName gets a reference to the given string and assigns it to the HeaderName field.
func (o *OAuthConfig) SetHeaderName(v string) {
	o.HeaderName = &v
}

// GetAuthHeaderPrefix returns the AuthHeaderPrefix field value if set, zero value otherwise.
func (o *OAuthConfig) GetAuthHeaderPrefix() string {
	if o == nil || IsNil(o.AuthHeaderPrefix) {
		var ret string
		return ret
	}
	return *o.AuthHeaderPrefix
}

// GetAuthHeaderPrefixOk returns a tuple with the AuthHeaderPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthConfig) GetAuthHeaderPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.AuthHeaderPrefix) {
		return nil, false
	}
	return o.AuthHeaderPrefix, true
}

// HasAuthHeaderPrefix returns a boolean if a field has been set.
func (o *OAuthConfig) HasAuthHeaderPrefix() bool {
	if o != nil && !IsNil(o.AuthHeaderPrefix) {
		return true
	}

	return false
}

// SetAuthHeaderPrefix gets a reference to the given string and assigns it to the AuthHeaderPrefix field.
func (o *OAuthConfig) SetAuthHeaderPrefix(v string) {
	o.AuthHeaderPrefix = &v
}

// GetForwardToken returns the ForwardToken field value if set, zero value otherwise.
func (o *OAuthConfig) GetForwardToken() bool {
	if o == nil || IsNil(o.ForwardToken) {
		var ret bool
		return ret
	}
	return *o.ForwardToken
}

// GetForwardTokenOk returns a tuple with the ForwardToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthConfig) GetForwardTokenOk() (*bool, bool) {
	if o == nil || IsNil(o.ForwardToken) {
		return nil, false
	}
	return o.ForwardToken, true
}

// HasForwardToken returns a boolean if a field has been set.
func (o *OAuthConfig) HasForwardToken() bool {
	if o != nil && !IsNil(o.ForwardToken) {
		return true
	}

	return false
}

// SetForwardToken gets a reference to the given bool and assigns it to the ForwardToken field.
func (o *OAuthConfig) SetForwardToken(v bool) {
	o.ForwardToken = &v
}

func (o OAuthConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuthConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Issuers) {
		toSerialize["issuers"] = o.Issuers
	}
	if !IsNil(o.Audiences) {
		toSerialize["audiences"] = o.Audiences
	}
	if !IsNil(o.HeaderName) {
		toSerialize["headerName"] = o.HeaderName
	}
	if !IsNil(o.AuthHeaderPrefix) {
		toSerialize["authHeaderPrefix"] = o.AuthHeaderPrefix
	}
	if !IsNil(o.ForwardToken) {
		toSerialize["forwardToken"] = o.ForwardToken
	}
	return toSerialize, nil
}

type NullableOAuthConfig struct {
	value *OAuthConfig
	isSet bool
}

func (v NullableOAuthConfig) Get() *OAuthConfig {
	return v.value
}

func (v *NullableOAuthConfig) Set(val *OAuthConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthConfig(val *OAuthConfig) *NullableOAuthConfig {
	return &NullableOAuthConfig{value: val, isSet: true}
}

func (v NullableOAuthConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
