// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"fmt"
	"log/slog"
	"time"

	"github.com/google/wire"
	"github.com/wso2/agent-manager/agent-manager-service/clients/observabilitysvc"
	"github.com/wso2/agent-manager/agent-manager-service/clients/openchoreosvc/client"
	"github.com/wso2/agent-manager/agent-manager-service/clients/secretmanagersvc"
	"github.com/wso2/agent-manager/agent-manager-service/clients/traceobserversvc"
	"github.com/wso2/agent-manager/agent-manager-service/config"
	"github.com/wso2/agent-manager/agent-manager-service/controllers"
	"github.com/wso2/agent-manager/agent-manager-service/eventhub"
	"github.com/wso2/agent-manager/agent-manager-service/instrumentation"
	"github.com/wso2/agent-manager/agent-manager-service/middleware/jwtassertion"
	"github.com/wso2/agent-manager/agent-manager-service/repositories"
	"github.com/wso2/agent-manager/agent-manager-service/services"
	"github.com/wso2/agent-manager/agent-manager-service/utils"
	"github.com/wso2/agent-manager/agent-manager-service/websocket"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeAppParams wires up all application dependencies
func InitializeAppParams(cfg *config.Config, db *gorm.DB, authProvider client.AuthProvider, secretProvider secretmanagersvc.Provider) (*AppParams, error) {
	configConfig := ProvideConfigFromPtr(cfg)
	middleware := ProvideAuthMiddleware(configConfig)
	logger := ProvideLogger()
	openChoreoClient, err := ProvideOCClient(configConfig, authProvider)
	if err != nil {
		return nil, err
	}
	observabilitySvcClient, err := ProvideObservabilitySvcClient(configConfig, authProvider)
	if err != nil {
		return nil, err
	}
	secretManagementClient, err := ProvideSecretManagementClient(configConfig, secretProvider, openChoreoClient)
	if err != nil {
		return nil, err
	}
	gitCredentialsService, err := ProvideGitCredentialsService(openChoreoClient, configConfig)
	if err != nil {
		return nil, err
	}
	repositoryService := services.NewRepositoryService(gitCredentialsService, logger)
	jwtSigningConfig := ProvideJWTSigningConfig(configConfig)
	agentTokenManagerService, err := services.NewAgentTokenManagerService(openChoreoClient, jwtSigningConfig, logger)
	if err != nil {
		return nil, err
	}
	agentConfigRepository := ProvideAgentConfigRepository(db)
	agentConfigurationRepository := repositories.NewAgentConfigurationRepository(db)
	envAgentModelMappingRepository := repositories.NewEnvAgentModelMappingRepository(db)
	agentEnvConfigVariableRepository := repositories.NewAgentEnvConfigVariableRepository(db)
	llmProviderRepository := ProvideLLMProviderRepository(db)
	gatewayRepository := ProvideGatewayRepository(db)
	llmProxyRepository := ProvideLLMProxyRepository(db)
	v, err := ProvideEncryptionKey(configConfig)
	if err != nil {
		return nil, err
	}
	llmProxyService := services.NewLLMProxyService(llmProxyRepository, llmProviderRepository, v)
	deploymentRepository := ProvideDeploymentRepository(db)
	eventHub, err := ProvideEventHub(db, logger)
	if err != nil {
		return nil, err
	}
	gatewayEventsService := services.NewGatewayEventsService(eventHub)
	llmProxyDeploymentService := services.NewLLMProxyDeploymentService(deploymentRepository, llmProxyRepository, llmProviderRepository, gatewayRepository, gatewayEventsService)
	apiKeyRepository := ProvideAPIKeyRepository(db)
	llmProxyAPIKeyService := services.NewLLMProxyAPIKeyService(llmProxyRepository, gatewayRepository, gatewayEventsService, apiKeyRepository)
	infraResourceManager := services.NewInfraResourceManager(openChoreoClient, logger)
	llmProviderAPIKeyService := services.NewLLMProviderAPIKeyService(llmProviderRepository, gatewayRepository, gatewayEventsService, apiKeyRepository)
	agentConfigurationService := services.NewAgentConfigurationService(db, agentConfigurationRepository, envAgentModelMappingRepository, agentEnvConfigVariableRepository, llmProviderRepository, gatewayRepository, llmProxyService, llmProxyDeploymentService, llmProxyAPIKeyService, infraResourceManager, openChoreoClient, llmProviderAPIKeyService, logger, secretManagementClient, v)
	agentKindRepository := ProvideAgentKindRepository(db)
	agentKindService := services.NewAgentKindService(agentKindRepository, openChoreoClient)
	artifactRepository := ProvideArtifactRepository(db)
	agentManagerService := services.NewAgentManagerService(db, openChoreoClient, observabilitySvcClient, secretManagementClient, repositoryService, agentTokenManagerService, agentConfigRepository, agentConfigurationService, agentKindService, artifactRepository, logger)
	agentController := controllers.NewAgentController(agentManagerService, agentKindService)
	agentKindController := controllers.NewAgentKindController(agentKindService)
	infraResourceController := controllers.NewInfraResourceController(infraResourceManager)
	agentTokenController := controllers.NewAgentTokenController(agentTokenManagerService)
	repositoryController := controllers.NewRepositoryController(repositoryService)
	environmentService := services.NewEnvironmentService(logger, gatewayRepository, openChoreoClient)
	environmentController := controllers.NewEnvironmentController(environmentService)
	platformGatewayService := services.NewPlatformGatewayService(gatewayRepository)
	gatewayController := controllers.NewGatewayController(platformGatewayService, openChoreoClient)
	llmProviderTemplateRepository := ProvideLLMProviderTemplateRepository(db)
	llmTemplateStore := services.NewLLMTemplateStore()
	llmProviderTemplateService := services.NewLLMProviderTemplateService(llmProviderTemplateRepository, llmTemplateStore)
	llmProviderService := services.NewLLMProviderService(db, llmProviderRepository, llmProviderTemplateRepository, llmTemplateStore, llmProxyRepository, artifactRepository, v, gatewayRepository)
	llmProviderDeploymentService := services.NewLLMProviderDeploymentService(deploymentRepository, llmProviderRepository, llmProviderTemplateRepository, gatewayRepository, gatewayEventsService)
	llmController := controllers.NewLLMController(llmProviderTemplateService, llmProviderService, llmProxyService, llmProviderDeploymentService, artifactRepository, openChoreoClient)
	llmDeploymentController := controllers.NewLLMDeploymentController(llmProviderDeploymentService)
	llmProviderAPIKeyController := controllers.NewLLMProviderAPIKeyController(llmProviderAPIKeyService)
	llmProxyAPIKeyController := controllers.NewLLMProxyAPIKeyController(llmProxyAPIKeyService)
	agentAPIKeyService := services.NewAgentAPIKeyService(artifactRepository, openChoreoClient, gatewayRepository, gatewayEventsService, apiKeyRepository)
	agentAPIKeyController := controllers.NewAgentAPIKeyController(agentAPIKeyService)
	llmProxyDeploymentController := controllers.NewLLMProxyDeploymentController(llmProxyDeploymentService)
	manager := ProvideWebSocketManager(configConfig, eventHub)
	deploymentAckHandler := ProvideDeploymentAckHandler(deploymentRepository)
	webSocketController := ProvideWebSocketController(manager, eventHub, platformGatewayService, deploymentAckHandler, configConfig)
	gatewayInternalAPIService := services.NewGatewayInternalAPIService(llmProviderRepository, llmProxyRepository, deploymentRepository, gatewayRepository, infraResourceManager, v)
	gatewayInternalController := controllers.NewGatewayInternalController(platformGatewayService, gatewayInternalAPIService, apiKeyRepository)
	monitorRepository := ProvideMonitorRepository(db)
	customEvaluatorRepository := ProvideCustomEvaluatorRepository(db)
	orgPublisherCredentialRepository := ProvideOrgPublisherCredentialRepository(db)
	monitorLLMMappingRepository := repositories.NewMonitorLLMMappingRepository(db)
	monitorExecutor := services.NewMonitorExecutor(openChoreoClient, logger, monitorRepository, customEvaluatorRepository, orgPublisherCredentialRepository, monitorLLMMappingRepository, gatewayRepository, llmProviderRepository)
	evaluatorManagerService := services.NewEvaluatorManagerService(logger, customEvaluatorRepository, monitorRepository)
	scoreRepository := ProvideScoreRepository(db)
	llmProxyProvisioner := services.NewLLMProxyProvisioner(logger, llmProviderRepository, gatewayRepository, llmProxyService, llmProxyDeploymentService, llmProxyAPIKeyService, llmProviderAPIKeyService, secretManagementClient, v)
	publisherCredentialProvisioner, err := ProvidePublisherProvisioner(configConfig, v, logger, secretManagementClient, openChoreoClient, orgPublisherCredentialRepository)
	if err != nil {
		return nil, err
	}
	monitorManagerService := services.NewMonitorManagerService(logger, db, openChoreoClient, observabilitySvcClient, monitorExecutor, evaluatorManagerService, monitorRepository, scoreRepository, llmProxyProvisioner, monitorLLMMappingRepository, publisherCredentialProvisioner)
	monitorController := controllers.NewMonitorController(monitorManagerService)
	monitorScoresService := services.NewMonitorScoresService(scoreRepository, monitorRepository, logger)
	monitorScoresController := controllers.NewMonitorScoresController(monitorScoresService)
	monitorScoresPublisherController := controllers.NewMonitorScoresPublisherController(monitorScoresService)
	evaluatorController := controllers.NewEvaluatorController(evaluatorManagerService)
	catalogRepository := ProvideCatalogRepository(db)
	catalogService := services.NewCatalogService(logger, catalogRepository, openChoreoClient)
	catalogController := controllers.NewCatalogController(catalogService)
	catalog, err := ProvideInstrumentationCatalog(configConfig)
	if err != nil {
		return nil, err
	}
	supportedPythonVersions := ProvideSupportedPythonVersions()
	wiringDefaultPythonVersion := ProvideDefaultPythonVersion()
	agentBuildOptionsController := ProvideAgentBuildOptionsController(catalog, supportedPythonVersions, wiringDefaultPythonVersion)
	agentConfigurationController := controllers.NewAgentConfigurationController(agentConfigurationService)
	gitSecretService := services.NewGitSecretService(openChoreoClient)
	gitSecretController := controllers.NewGitSecretController(gitSecretService)
	monitorSchedulerService := services.NewMonitorSchedulerService(openChoreoClient, publisherCredentialProvisioner, logger, monitorExecutor, monitorRepository)
	traceObserverSvcClient, err := ProvideTraceObserverClient(configConfig, authProvider)
	if err != nil {
		return nil, err
	}
	appParams := &AppParams{
		AuthMiddleware:                   middleware,
		Logger:                           logger,
		AgentController:                  agentController,
		AgentKindController:              agentKindController,
		InfraResourceController:          infraResourceController,
		AgentTokenController:             agentTokenController,
		RepositoryController:             repositoryController,
		EnvironmentController:            environmentController,
		GatewayController:                gatewayController,
		LLMController:                    llmController,
		LLMDeploymentController:          llmDeploymentController,
		LLMProviderAPIKeyController:      llmProviderAPIKeyController,
		LLMProxyAPIKeyController:         llmProxyAPIKeyController,
		AgentAPIKeyController:            agentAPIKeyController,
		LLMProxyDeploymentController:     llmProxyDeploymentController,
		WebSocketController:              webSocketController,
		GatewayInternalController:        gatewayInternalController,
		MonitorController:                monitorController,
		MonitorScoresController:          monitorScoresController,
		MonitorScoresPublisherController: monitorScoresPublisherController,
		EvaluatorController:              evaluatorController,
		CatalogController:                catalogController,
		AgentBuildOptionsController:      agentBuildOptionsController,
		AgentConfigurationController:     agentConfigurationController,
		GitSecretController:              gitSecretController,
		MonitorScheduler:                 monitorSchedulerService,
		LLMTemplateStore:                 llmTemplateStore,
		InfraResourceManager:             infraResourceManager,
		AgentManagerService:              agentManagerService,
		AgentTokenManagerService:         agentTokenManagerService,
		OpenChoreoClient:                 openChoreoClient,
		TraceObserverSvcClient:           traceObserverSvcClient,
		WebSocketManager:                 manager,
		EventHub:                         eventHub,
		DB:                               db,
	}
	return appParams, nil
}

// InitializeTestAppParamsWithClientMocks wires up application dependencies with test mocks
func InitializeTestAppParamsWithClientMocks(cfg *config.Config, db *gorm.DB, authMiddleware jwtassertion.Middleware, testClients TestClients) (*AppParams, error) {
	logger := ProvideLogger()
	openChoreoClient := ProvideTestOpenChoreoClient(testClients)
	observabilitySvcClient := ProvideTestObservabilitySvcClient(testClients)
	secretManagementClient := ProvideTestSecretManagementClient(testClients)
	configConfig := ProvideConfigFromPtr(cfg)
	gitCredentialsService, err := ProvideGitCredentialsService(openChoreoClient, configConfig)
	if err != nil {
		return nil, err
	}
	repositoryService := services.NewRepositoryService(gitCredentialsService, logger)
	jwtSigningConfig := ProvideJWTSigningConfig(configConfig)
	agentTokenManagerService, err := services.NewAgentTokenManagerService(openChoreoClient, jwtSigningConfig, logger)
	if err != nil {
		return nil, err
	}
	agentConfigRepository := ProvideAgentConfigRepository(db)
	agentConfigurationRepository := repositories.NewAgentConfigurationRepository(db)
	envAgentModelMappingRepository := repositories.NewEnvAgentModelMappingRepository(db)
	agentEnvConfigVariableRepository := repositories.NewAgentEnvConfigVariableRepository(db)
	llmProviderRepository := ProvideLLMProviderRepository(db)
	gatewayRepository := ProvideGatewayRepository(db)
	llmProxyRepository := ProvideLLMProxyRepository(db)
	v, err := ProvideEncryptionKey(configConfig)
	if err != nil {
		return nil, err
	}
	llmProxyService := services.NewLLMProxyService(llmProxyRepository, llmProviderRepository, v)
	deploymentRepository := ProvideDeploymentRepository(db)
	eventHub, err := ProvideEventHub(db, logger)
	if err != nil {
		return nil, err
	}
	gatewayEventsService := services.NewGatewayEventsService(eventHub)
	llmProxyDeploymentService := services.NewLLMProxyDeploymentService(deploymentRepository, llmProxyRepository, llmProviderRepository, gatewayRepository, gatewayEventsService)
	apiKeyRepository := ProvideAPIKeyRepository(db)
	llmProxyAPIKeyService := services.NewLLMProxyAPIKeyService(llmProxyRepository, gatewayRepository, gatewayEventsService, apiKeyRepository)
	infraResourceManager := services.NewInfraResourceManager(openChoreoClient, logger)
	llmProviderAPIKeyService := services.NewLLMProviderAPIKeyService(llmProviderRepository, gatewayRepository, gatewayEventsService, apiKeyRepository)
	agentConfigurationService := services.NewAgentConfigurationService(db, agentConfigurationRepository, envAgentModelMappingRepository, agentEnvConfigVariableRepository, llmProviderRepository, gatewayRepository, llmProxyService, llmProxyDeploymentService, llmProxyAPIKeyService, infraResourceManager, openChoreoClient, llmProviderAPIKeyService, logger, secretManagementClient, v)
	agentKindRepository := ProvideAgentKindRepository(db)
	agentKindService := services.NewAgentKindService(agentKindRepository, openChoreoClient)
	artifactRepository := ProvideArtifactRepository(db)
	agentManagerService := services.NewAgentManagerService(db, openChoreoClient, observabilitySvcClient, secretManagementClient, repositoryService, agentTokenManagerService, agentConfigRepository, agentConfigurationService, agentKindService, artifactRepository, logger)
	agentController := controllers.NewAgentController(agentManagerService, agentKindService)
	agentKindController := controllers.NewAgentKindController(agentKindService)
	infraResourceController := controllers.NewInfraResourceController(infraResourceManager)
	agentTokenController := controllers.NewAgentTokenController(agentTokenManagerService)
	repositoryController := controllers.NewRepositoryController(repositoryService)
	environmentService := services.NewEnvironmentService(logger, gatewayRepository, openChoreoClient)
	environmentController := controllers.NewEnvironmentController(environmentService)
	platformGatewayService := services.NewPlatformGatewayService(gatewayRepository)
	gatewayController := controllers.NewGatewayController(platformGatewayService, openChoreoClient)
	llmProviderTemplateRepository := ProvideLLMProviderTemplateRepository(db)
	llmTemplateStore := services.NewLLMTemplateStore()
	llmProviderTemplateService := services.NewLLMProviderTemplateService(llmProviderTemplateRepository, llmTemplateStore)
	llmProviderService := services.NewLLMProviderService(db, llmProviderRepository, llmProviderTemplateRepository, llmTemplateStore, llmProxyRepository, artifactRepository, v, gatewayRepository)
	llmProviderDeploymentService := services.NewLLMProviderDeploymentService(deploymentRepository, llmProviderRepository, llmProviderTemplateRepository, gatewayRepository, gatewayEventsService)
	llmController := controllers.NewLLMController(llmProviderTemplateService, llmProviderService, llmProxyService, llmProviderDeploymentService, artifactRepository, openChoreoClient)
	llmDeploymentController := controllers.NewLLMDeploymentController(llmProviderDeploymentService)
	llmProviderAPIKeyController := controllers.NewLLMProviderAPIKeyController(llmProviderAPIKeyService)
	llmProxyAPIKeyController := controllers.NewLLMProxyAPIKeyController(llmProxyAPIKeyService)
	agentAPIKeyService := services.NewAgentAPIKeyService(artifactRepository, openChoreoClient, gatewayRepository, gatewayEventsService, apiKeyRepository)
	agentAPIKeyController := controllers.NewAgentAPIKeyController(agentAPIKeyService)
	llmProxyDeploymentController := controllers.NewLLMProxyDeploymentController(llmProxyDeploymentService)
	manager := ProvideWebSocketManager(configConfig, eventHub)
	deploymentAckHandler := ProvideDeploymentAckHandler(deploymentRepository)
	webSocketController := ProvideWebSocketController(manager, eventHub, platformGatewayService, deploymentAckHandler, configConfig)
	gatewayInternalAPIService := services.NewGatewayInternalAPIService(llmProviderRepository, llmProxyRepository, deploymentRepository, gatewayRepository, infraResourceManager, v)
	gatewayInternalController := controllers.NewGatewayInternalController(platformGatewayService, gatewayInternalAPIService, apiKeyRepository)
	monitorRepository := ProvideMonitorRepository(db)
	customEvaluatorRepository := ProvideCustomEvaluatorRepository(db)
	orgPublisherCredentialRepository := ProvideOrgPublisherCredentialRepository(db)
	monitorLLMMappingRepository := repositories.NewMonitorLLMMappingRepository(db)
	monitorExecutor := services.NewMonitorExecutor(openChoreoClient, logger, monitorRepository, customEvaluatorRepository, orgPublisherCredentialRepository, monitorLLMMappingRepository, gatewayRepository, llmProviderRepository)
	evaluatorManagerService := services.NewEvaluatorManagerService(logger, customEvaluatorRepository, monitorRepository)
	scoreRepository := ProvideScoreRepository(db)
	llmProxyProvisioner := services.NewLLMProxyProvisioner(logger, llmProviderRepository, gatewayRepository, llmProxyService, llmProxyDeploymentService, llmProxyAPIKeyService, llmProviderAPIKeyService, secretManagementClient, v)
	publisherCredentialProvisioner, err := ProvidePublisherProvisioner(configConfig, v, logger, secretManagementClient, openChoreoClient, orgPublisherCredentialRepository)
	if err != nil {
		return nil, err
	}
	monitorManagerService := services.NewMonitorManagerService(logger, db, openChoreoClient, observabilitySvcClient, monitorExecutor, evaluatorManagerService, monitorRepository, scoreRepository, llmProxyProvisioner, monitorLLMMappingRepository, publisherCredentialProvisioner)
	monitorController := controllers.NewMonitorController(monitorManagerService)
	monitorScoresService := services.NewMonitorScoresService(scoreRepository, monitorRepository, logger)
	monitorScoresController := controllers.NewMonitorScoresController(monitorScoresService)
	monitorScoresPublisherController := controllers.NewMonitorScoresPublisherController(monitorScoresService)
	evaluatorController := controllers.NewEvaluatorController(evaluatorManagerService)
	catalogRepository := ProvideCatalogRepository(db)
	catalogService := services.NewCatalogService(logger, catalogRepository, openChoreoClient)
	catalogController := controllers.NewCatalogController(catalogService)
	catalog, err := ProvideInstrumentationCatalog(configConfig)
	if err != nil {
		return nil, err
	}
	supportedPythonVersions := ProvideSupportedPythonVersions()
	wiringDefaultPythonVersion := ProvideDefaultPythonVersion()
	agentBuildOptionsController := ProvideAgentBuildOptionsController(catalog, supportedPythonVersions, wiringDefaultPythonVersion)
	agentConfigurationController := controllers.NewAgentConfigurationController(agentConfigurationService)
	gitSecretService := services.NewGitSecretService(openChoreoClient)
	gitSecretController := controllers.NewGitSecretController(gitSecretService)
	monitorSchedulerService := services.NewMonitorSchedulerService(openChoreoClient, publisherCredentialProvisioner, logger, monitorExecutor, monitorRepository)
	traceObserverSvcClient := ProvideTestTraceObserverClient(testClients)
	appParams := &AppParams{
		AuthMiddleware:                   authMiddleware,
		Logger:                           logger,
		AgentController:                  agentController,
		AgentKindController:              agentKindController,
		InfraResourceController:          infraResourceController,
		AgentTokenController:             agentTokenController,
		RepositoryController:             repositoryController,
		EnvironmentController:            environmentController,
		GatewayController:                gatewayController,
		LLMController:                    llmController,
		LLMDeploymentController:          llmDeploymentController,
		LLMProviderAPIKeyController:      llmProviderAPIKeyController,
		LLMProxyAPIKeyController:         llmProxyAPIKeyController,
		AgentAPIKeyController:            agentAPIKeyController,
		LLMProxyDeploymentController:     llmProxyDeploymentController,
		WebSocketController:              webSocketController,
		GatewayInternalController:        gatewayInternalController,
		MonitorController:                monitorController,
		MonitorScoresController:          monitorScoresController,
		MonitorScoresPublisherController: monitorScoresPublisherController,
		EvaluatorController:              evaluatorController,
		CatalogController:                catalogController,
		AgentBuildOptionsController:      agentBuildOptionsController,
		AgentConfigurationController:     agentConfigurationController,
		GitSecretController:              gitSecretController,
		MonitorScheduler:                 monitorSchedulerService,
		LLMTemplateStore:                 llmTemplateStore,
		InfraResourceManager:             infraResourceManager,
		AgentManagerService:              agentManagerService,
		AgentTokenManagerService:         agentTokenManagerService,
		OpenChoreoClient:                 openChoreoClient,
		TraceObserverSvcClient:           traceObserverSvcClient,
		WebSocketManager:                 manager,
		EventHub:                         eventHub,
		DB:                               db,
	}
	return appParams, nil
}

// wire.go:

// Provider sets
var configProviderSet = wire.NewSet(
	ProvideConfigFromPtr,
	ProvideEncryptionKey,
)

var clientProviderSet = wire.NewSet(
	ProvideObservabilitySvcClient,
	ProvideTraceObserverClient,
	ProvideOCClient,
	ProvideSecretManagementClient,
	ProvidePublisherProvisioner,
)

var serviceProviderSet = wire.NewSet(services.NewAgentManagerService, services.NewAgentKindService, services.NewInfraResourceManager, services.NewAgentTokenManagerService, ProvideGitCredentialsService, services.NewRepositoryService, services.NewMonitorExecutor, services.NewMonitorManagerService, ProvideThunderConfig, services.NewMonitorSchedulerService, services.NewEvaluatorManagerService, services.NewEnvironmentService, services.NewPlatformGatewayService, services.NewLLMProviderTemplateService, services.NewLLMProviderService, services.NewLLMProxyService, services.NewLLMProviderDeploymentService, services.NewLLMProviderAPIKeyService, services.NewLLMProxyAPIKeyService, services.NewAgentAPIKeyService, services.NewLLMProxyDeploymentService, services.NewGatewayInternalAPIService, services.NewMonitorScoresService, services.NewCatalogService, services.NewLLMProxyProvisioner, services.NewAgentConfigurationService, services.NewLLMTemplateStore, services.NewGitSecretService)

var instrumentationProviderSet = wire.NewSet(
	ProvideInstrumentationCatalog,
	ProvideSupportedPythonVersions,
	ProvideDefaultPythonVersion,
)

var controllerProviderSet = wire.NewSet(controllers.NewAgentController, controllers.NewAgentKindController, controllers.NewInfraResourceController, controllers.NewAgentTokenController, controllers.NewRepositoryController, controllers.NewEnvironmentController, controllers.NewGatewayController, controllers.NewLLMController, controllers.NewLLMDeploymentController, controllers.NewLLMProviderAPIKeyController, controllers.NewLLMProxyAPIKeyController, controllers.NewAgentAPIKeyController, controllers.NewLLMProxyDeploymentController, ProvideWebSocketController, controllers.NewGatewayInternalController, controllers.NewMonitorController, controllers.NewMonitorScoresController, controllers.NewMonitorScoresPublisherController, controllers.NewEvaluatorController, controllers.NewCatalogController, ProvideAgentBuildOptionsController, controllers.NewAgentConfigurationController, controllers.NewGitSecretController)

var testClientProviderSet = wire.NewSet(
	ProvideTestOpenChoreoClient,
	ProvideTestObservabilitySvcClient,
	ProvideTestTraceObserverClient,
	ProvideTestSecretManagementClient,
	ProvidePublisherProvisioner,
)

// ProvideLogger provides the configured slog.Logger instance
func ProvideLogger() *slog.Logger {
	return slog.Default()
}

// ProvideInstrumentationCatalog loads the instrumentation catalog and
// installs it as the process-wide default so legacy callers via
// instrumentation.GetCatalog get the same instance Wire hands to the new
// controllers.
func ProvideInstrumentationCatalog(cfg config.Config) (*instrumentation.Catalog, error) {
	cat, err := instrumentation.Load(
		cfg.OTEL.InstrumentationExtensionPath,
		cfg.OTEL.DefaultInstrumentationVersion,
	)
	if err != nil {
		return nil, err
	}
	if err := validateDefaultCoversBuildpackPython(cat); err != nil {
		return nil, err
	}
	instrumentation.SetCatalog(cat)
	return cat, nil
}

// validateDefaultCoversBuildpackPython rejects a catalog whose default
// instrumentation entry doesn't cover any Python the buildpack provider
// can build. Without this check a misconfigured override (e.g. an
// extension entry that narrows the default's pythonVersions to a value
// the buildpack can't build) lets the server boot cleanly, then the
// create-agent form is unusable: no Python the user can pick is
// compatible with the platform default. Failing fast here surfaces the
// misconfiguration at helm-upgrade time instead.
func validateDefaultCoversBuildpackPython(cat *instrumentation.Catalog) error {
	entry, ok := cat.Get(cat.Default())
	if !ok {

		return fmt.Errorf("default instrumentation version %q not in effective set", cat.Default())
	}
	bpPython := utils.SupportedPythonVersions()
	for _, p := range entry.PythonVersions {
		for _, bp := range bpPython {
			if p == bp {
				return nil
			}
		}
	}
	return fmt.Errorf(
		"default instrumentation version %q supports python %v but the buildpack provider supports %v; no overlap means the create-agent form would offer no valid combination",
		cat.Default(), entry.PythonVersions, bpPython,
	)
}

// SupportedPythonVersions is a distinct type so Wire can disambiguate
// from other []string providers.
type SupportedPythonVersions []string

// DefaultPythonVersion is a distinct type so Wire can disambiguate from
// other string providers.
type DefaultPythonVersion string

// ProvideSupportedPythonVersions exposes the buildpack-derived Python
// list to the AgentBuildOptions controller.
func ProvideSupportedPythonVersions() SupportedPythonVersions {
	return SupportedPythonVersions(utils.SupportedPythonVersions())
}

// defaultPythonVersion is the platform's preferred Python for new
// agents. Hardcoded today; promote to a chart value if customers need
// to override it per install.
const defaultPythonVersion = "3.11"

// ProvideDefaultPythonVersion returns the platform default Python
// version, panicking at boot if the constant is no longer present in
// the buildpack-supported list. The two values share no compile-time
// link; without this guard a developer pruning utils.Buildpacks could
// ship a chart whose /agent-build-options advertises a default the
// backend then rejects.
func ProvideDefaultPythonVersion() DefaultPythonVersion {
	for _, p := range utils.SupportedPythonVersions() {
		if p == defaultPythonVersion {
			return defaultPythonVersion
		}
	}
	panic(fmt.Sprintf(
		"default python version %q not present in buildpack-supported list %v; "+
			"update defaultPythonVersion in wire.go alongside any buildpack change",
		defaultPythonVersion, utils.SupportedPythonVersions(),
	))
}

// ProvideAgentBuildOptionsController wraps the controller constructor
// so Wire can resolve the typed default + supported list back to the
// plain string / []string the constructor takes.
func ProvideAgentBuildOptionsController(
	cat *instrumentation.Catalog,
	supportedPython SupportedPythonVersions,
	defaultPython DefaultPythonVersion,
) controllers.AgentBuildOptionsController {
	return controllers.NewAgentBuildOptionsController(cat, []string(supportedPython), string(defaultPython))
}

// ProvideOCClient creates the OpenChoreo client
func ProvideOCClient(cfg config.Config, authProvider client.AuthProvider) (client.OpenChoreoClient, error) {
	return client.NewOpenChoreoClient(&client.Config{
		BaseURL:      cfg.OpenChoreo.BaseURL,
		AuthProvider: authProvider,
	})
}

// ProvideObservabilitySvcClient creates the observability service client
func ProvideObservabilitySvcClient(cfg config.Config, authProvider client.AuthProvider) (observabilitysvc.ObservabilitySvcClient, error) {
	return observabilitysvc.NewObservabilitySvcClient(&observabilitysvc.Config{
		BaseURL:      cfg.Observer.URL,
		AuthProvider: authProvider,
	})
}

func ProvideTraceObserverClient(cfg config.Config, authProvider client.AuthProvider) (traceobserversvc.TraceObserverSvcClient, error) {
	return traceobserversvc.NewTraceObserverClient(&traceobserversvc.Config{
		BaseURL:      cfg.TraceObserver.URL,
		AuthProvider: authProvider,
	})
}

// ProvideSecretManagementClient creates the secret management service client.
// If the provider implements secretmanagersvc.SecretReferenceManager and
// reports that it manages SecretReferences itself, the OpenChoreo client is
// not forwarded — preventing the high-level client from making redundant
// SecretReference CRUD calls.
func ProvideSecretManagementClient(cfg config.Config, secretProvider secretmanagersvc.Provider, ocClient client.OpenChoreoClient) (secretmanagersvc.SecretManagementClient, error) {
	ocClientForSecretMgmt := ocClient
	if mgr, ok := secretProvider.(secretmanagersvc.SecretReferenceManager); ok && mgr.ManagesSecretReferences() {
		ocClientForSecretMgmt = nil
	}
	return secretmanagersvc.NewSecretManagementClientWithConfig(secretmanagersvc.SecretManagementClientConfig{
		StoreConfig: &secretmanagersvc.StoreConfig{
			Provider: cfg.SecretManager.Provider,
			OpenBao: &secretmanagersvc.OpenBaoConfig{
				Server: cfg.OpenBao.URL,
				Path:   cfg.OpenBao.Path,
				Auth: &secretmanagersvc.OpenBaoAuth{
					Token: cfg.OpenBao.Token,
				},
			},
		},
		Provider:        secretProvider,
		OCClient:        ocClientForSecretMgmt,
		RefreshInterval: cfg.SecretManager.RefreshInterval,
	})
}

// ProvideGitCredentialsService creates the git credentials service for fetching
// git credentials from workflow plane OpenBao
func ProvideGitCredentialsService(ocClient client.OpenChoreoClient, cfg config.Config) (services.GitCredentialsService, error) {
	return services.NewGitCredentialsService(ocClient, cfg)
}

// ProvidePublisherProvisioner creates the publisher credential provisioner
// for per-org Thunder OAuth app creation and secret storage via SecretManagementClient
func ProvidePublisherProvisioner(cfg config.Config, encryptionKey []byte, logger *slog.Logger, secretClient secretmanagersvc.SecretManagementClient, ocClient client.OpenChoreoClient, credRepo repositories.OrgPublisherCredentialRepository) (services.PublisherCredentialProvisioner, error) {
	return services.NewPublisherCredentialProvisioner(cfg, encryptionKey, logger, secretClient, ocClient, credRepo)
}

var loggerProviderSet = wire.NewSet(
	ProvideLogger,
)

var repositoryProviderSet = wire.NewSet(
	ProvideGatewayRepository,
	ProvideAgentKindRepository,
	ProvideLLMProviderTemplateRepository,
	ProvideLLMProviderRepository,
	ProvideLLMProxyRepository,
	ProvideDeploymentRepository,
	ProvideArtifactRepository,
	ProvideScoreRepository,
	ProvideCatalogRepository,
	ProvideMonitorRepository,
	ProvideAgentConfigRepository,
	ProvideCustomEvaluatorRepository,
	ProvideAPIKeyRepository, repositories.NewAgentConfigurationRepository, repositories.NewEnvAgentModelMappingRepository, repositories.NewAgentEnvConfigVariableRepository, repositories.NewMonitorLLMMappingRepository, ProvideOrgPublisherCredentialRepository,
)

var websocketProviderSet = wire.NewSet(
	ProvideEventHub,
	ProvideWebSocketManager, services.NewGatewayEventsService, ProvideDeploymentAckHandler,
)

// Test client providers
func ProvideTestOpenChoreoClient(testClients TestClients) client.OpenChoreoClient {
	return testClients.OpenChoreoClient
}

func ProvideTestObservabilitySvcClient(testClients TestClients) observabilitysvc.ObservabilitySvcClient {
	return testClients.ObservabilitySvcClient
}

func ProvideTestTraceObserverClient(testClients TestClients) traceobserversvc.TraceObserverSvcClient {
	return testClients.TraceObserverSvcClient
}

func ProvideTestSecretManagementClient(testClients TestClients) secretmanagersvc.SecretManagementClient {
	return testClients.SecretMgmtClient
}

// ProvideEventHub creates and initializes the EventHub backed by PostgreSQL.
func ProvideEventHub(db *gorm.DB, logger *slog.Logger) (eventhub.EventHub, error) {
	sqlDB, err := db.DB()
	if err != nil {
		return nil, err
	}
	cfg := eventhub.DefaultSQLBackendConfig()
	hub := eventhub.NewSQLBackend(sqlDB, logger, cfg)
	if err := hub.Initialize(); err != nil {
		return nil, err
	}
	return hub, nil
}

// ProvideWebSocketManager creates a new WebSocket manager with config
func ProvideWebSocketManager(cfg config.Config, hub eventhub.EventHub) *websocket.Manager {
	wsConfig := websocket.ManagerConfig{
		MaxConnections:    cfg.WebSocket.MaxConnections,
		HeartbeatInterval: 20 * time.Second,
		HeartbeatTimeout:  time.Duration(cfg.WebSocket.ConnectionTimeout) * time.Second,
	}
	return websocket.NewManager(wsConfig, hub)
}

// ProvideWebSocketController creates a new WebSocket controller with rate limiting
func ProvideWebSocketController(
	manager *websocket.Manager,
	hub eventhub.EventHub,
	gatewayService *services.PlatformGatewayService,
	ackHandler *services.DeploymentAckHandler,
	cfg config.Config,
) controllers.WebSocketController {
	rateLimitCount := cfg.WebSocket.RateLimitPerMin
	return controllers.NewWebSocketController(manager, hub, gatewayService, ackHandler, rateLimitCount)
}

// ProvideDeploymentAckHandler creates a new deployment ack handler
func ProvideDeploymentAckHandler(deploymentRepo repositories.DeploymentRepository) *services.DeploymentAckHandler {
	return services.NewDeploymentAckHandler(deploymentRepo)
}

func ProvideGatewayRepository(db *gorm.DB) repositories.GatewayRepository {
	return repositories.NewGatewayRepo(db)
}

func ProvideLLMProviderTemplateRepository(db *gorm.DB) repositories.LLMProviderTemplateRepository {
	return repositories.NewLLMProviderTemplateRepo(db)
}

func ProvideLLMProviderRepository(db *gorm.DB) repositories.LLMProviderRepository {
	return repositories.NewLLMProviderRepo(db)
}

func ProvideLLMProxyRepository(db *gorm.DB) repositories.LLMProxyRepository {
	return repositories.NewLLMProxyRepo(db)
}

func ProvideDeploymentRepository(db *gorm.DB) repositories.DeploymentRepository {
	return repositories.NewDeploymentRepo(db)
}

func ProvideArtifactRepository(db *gorm.DB) repositories.ArtifactRepository {
	return repositories.NewArtifactRepo(db)
}

func ProvideAPIKeyRepository(db *gorm.DB) repositories.APIKeyRepository {
	return repositories.NewAPIKeyRepo(db)
}

func ProvideScoreRepository(db *gorm.DB) repositories.ScoreRepository {
	return repositories.NewScoreRepo(db)
}

func ProvideCatalogRepository(db *gorm.DB) repositories.CatalogRepository {
	return repositories.NewCatalogRepo(db)
}

func ProvideMonitorRepository(db *gorm.DB) repositories.MonitorRepository {
	return repositories.NewMonitorRepo(db)
}

func ProvideAgentConfigRepository(db *gorm.DB) repositories.AgentConfigRepository {
	return repositories.NewAgentConfigRepo(db)
}

func ProvideCustomEvaluatorRepository(db *gorm.DB) repositories.CustomEvaluatorRepository {
	return repositories.NewCustomEvaluatorRepo(db)
}

func ProvideOrgPublisherCredentialRepository(db *gorm.DB) repositories.OrgPublisherCredentialRepository {
	return repositories.NewOrgPublisherCredentialRepo(db)
}

func ProvideAgentKindRepository(db *gorm.DB) repositories.AgentKindRepository {
	return repositories.NewAgentKindRepo(db)
}

func ProvideThunderConfig(cfg config.Config) config.ThunderConfig {
	return cfg.Thunder
}
