// Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package services

import (
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"

	"github.com/wso2/agent-manager/agent-manager-service/models"
	"github.com/wso2/agent-manager/agent-manager-service/repositories"
	"github.com/wso2/agent-manager/agent-manager-service/utils"
)

// MonitorScoresService handles evaluation score business logic
type MonitorScoresService struct {
	repo        repositories.ScoreRepository
	monitorRepo repositories.MonitorRepository
	logger      *slog.Logger
}

// NewMonitorScoresService creates a new monitor scores service
func NewMonitorScoresService(
	repo repositories.ScoreRepository,
	monitorRepo repositories.MonitorRepository,
	logger *slog.Logger,
) *MonitorScoresService {
	return &MonitorScoresService{
		repo:        repo,
		monitorRepo: monitorRepo,
		logger:      logger,
	}
}

// PublishScores stores evaluation scores and aggregates for a monitor run
func (s *MonitorScoresService) PublishScores(
	monitorID, runID uuid.UUID,
	req *models.PublishScoresRequest,
) error {
	// Step 1: Build run evaluators (IDs generated by DB via gen_random_uuid())
	runEvaluators := make([]models.MonitorRunEvaluator, len(req.AggregatedScores))
	for i, item := range req.AggregatedScores {
		runEvaluators[i] = models.MonitorRunEvaluator{
			MonitorRunID:  runID,
			MonitorID:     monitorID,
			Identifier:    item.Identifier,
			EvaluatorName: item.EvaluatorName,
			Level:         item.Level,
			Aggregations:  item.Aggregations,
			Count:         item.Count,
			SkippedCount:  item.SkippedCount,
		}
	}

	// Step 2: Validate individual scores before starting the transaction
	for _, item := range req.IndividualScores {
		if item.TraceStartTime == nil {
			return fmt.Errorf("traceStartTime is required for score with traceID %s", item.TraceID)
		}
	}

	// Step 3: Upsert evaluators and scores atomically
	if err := s.repo.RunInTransaction(func(txRepo repositories.ScoreRepository) error {
		if err := txRepo.UpsertMonitorRunEvaluators(runEvaluators); err != nil {
			return fmt.Errorf("failed to upsert run evaluators: %w", err)
		}

		// Reload evaluators to get the actual DB-generated IDs (upsert may keep existing IDs on conflict)
		dbEvaluators, err := txRepo.GetEvaluatorsByMonitorAndRunID(monitorID, runID)
		if err != nil {
			return fmt.Errorf("failed to reload run evaluators: %w", err)
		}

		evaluatorMap := make(map[string]uuid.UUID)
		for _, re := range dbEvaluators {
			evaluatorMap[re.EvaluatorName] = re.ID
		}

		// Collect current run evaluator IDs and trace IDs for stale score cleanup
		currentRunEvaluatorIDs := make([]uuid.UUID, len(dbEvaluators))
		for i, re := range dbEvaluators {
			currentRunEvaluatorIDs[i] = re.ID
		}

		traceIDSet := make(map[string]struct{})
		for _, item := range req.IndividualScores {
			traceIDSet[item.TraceID] = struct{}{}
		}
		traceIDs := make([]string, 0, len(traceIDSet))
		for tid := range traceIDSet {
			traceIDs = append(traceIDs, tid)
		}

		// Delete stale scores from previous runs before inserting new ones
		if err := txRepo.DeleteStaleScores(monitorID, currentRunEvaluatorIDs, traceIDs); err != nil {
			return fmt.Errorf("failed to delete stale scores: %w", err)
		}

		// Build scores using the real DB IDs
		scores := make([]models.Score, len(req.IndividualScores))
		for i, item := range req.IndividualScores {
			runEvaluatorID, exists := evaluatorMap[item.EvaluatorName]
			if !exists {
				return fmt.Errorf("evaluator %s not found in evaluators list", item.EvaluatorName)
			}

			// Extract span context fields
			var spanID *string
			spanLabel := ""
			if sc := item.SpanContext; sc != nil {
				spanID = sc.SpanID
				switch item.Level {
				case "agent":
					if sc.AgentName != nil && *sc.AgentName != "" {
						spanLabel = *sc.AgentName
					}
				case "llm":
					if sc.Model != nil && *sc.Model != "" {
						if sc.Vendor != nil && *sc.Vendor != "" {
							spanLabel = *sc.Vendor + "/" + *sc.Model
						} else {
							spanLabel = *sc.Model
						}
					}
				}
			}

			scores[i] = models.Score{
				RunEvaluatorID: runEvaluatorID,
				MonitorID:      monitorID,
				TraceID:        item.TraceID,
				SpanID:         spanID,
				Score:          item.Score,
				Explanation:    item.Explanation,
				TraceStartTime: *item.TraceStartTime,
				SkipReason:     item.SkipReason,
				SpanLabel:      spanLabel,
			}
		}

		if err := txRepo.BatchCreateScores(scores); err != nil {
			return fmt.Errorf("failed to create scores: %w", err)
		}

		return nil
	}); err != nil {
		return err
	}

	s.logger.Info("Published evaluation scores",
		"monitorID", monitorID,
		"runID", runID,
		"scoreCount", len(req.IndividualScores),
		"evaluatorCount", len(runEvaluators))

	return nil
}

// GetMonitorScores returns aggregated scores for a monitor within a time range
func (s *MonitorScoresService) GetMonitorScores(
	monitorID uuid.UUID,
	monitorName string,
	startTime, endTime time.Time,
	filters repositories.ScoreFilters,
) (*models.MonitorScoresResponse, error) {
	// Use SQL aggregation query instead of fetching all rows
	aggregations, err := s.repo.GetMonitorScoresAggregated(monitorID, startTime, endTime, filters)
	if err != nil {
		return nil, fmt.Errorf("failed to get aggregated scores: %w", err)
	}

	// Convert aggregations to response format
	evaluators := make([]models.EvaluatorScoreSummary, len(aggregations))
	for i, agg := range aggregations {
		aggregationMap := make(map[string]interface{})
		if agg.MeanScore != nil {
			aggregationMap["mean"] = *agg.MeanScore
		} else {
			aggregationMap["mean"] = nil
		}

		evaluators[i] = models.EvaluatorScoreSummary{
			EvaluatorName: agg.EvaluatorName,
			Level:         agg.Level,
			Count:         agg.TotalCount,
			SkippedCount:  agg.SkippedCount,
			Aggregations:  aggregationMap,
		}
	}

	return &models.MonitorScoresResponse{
		MonitorName: monitorName,
		TimeRange: models.TimeRange{
			Start: startTime,
			End:   endTime,
		},
		Evaluators: evaluators,
	}, nil
}

// GetEvaluatorsTimeSeries returns batch time-series data for multiple evaluators.
// All evaluators share a single granularity determined by combined data density.
// Uses at most 2 DB queries regardless of evaluator count.
func (s *MonitorScoresService) GetEvaluatorsTimeSeries(
	monitorID uuid.UUID,
	monitorName string,
	evaluatorNames []string,
	startTime, endTime time.Time,
) (*models.BatchTimeSeriesResponse, error) {
	probeLimit := int(utils.RawThreshold) + 1

	// Phase 1: Probe — fetch up to RawThreshold+1 rows across all evaluators combined
	traceAggs, err := s.repo.GetEvaluatorsTraceAggregated(monitorID, evaluatorNames, startTime, endTime, probeLimit)
	if err != nil {
		return nil, fmt.Errorf("failed to probe batch trace aggregations: %w", err)
	}

	isSparse := len(traceAggs) <= int(utils.RawThreshold)

	var granularity string
	evaluatorPoints := make(map[string][]models.TimeSeriesPoint, len(evaluatorNames))

	if isSparse {
		// Sparse path: use trace-level points directly from the probe result
		granularity = "trace"
		for _, agg := range traceAggs {
			aggMap := make(map[string]interface{})
			if agg.MeanScore != nil {
				aggMap["mean"] = *agg.MeanScore
			} else {
				aggMap["mean"] = nil
			}
			evaluatorPoints[agg.EvaluatorName] = append(evaluatorPoints[agg.EvaluatorName], models.TimeSeriesPoint{
				Timestamp:    agg.TraceStartTime,
				Count:        agg.TotalCount,
				SkippedCount: agg.SkippedCount,
				Aggregations: aggMap,
			})
		}
	} else {
		// Dense path: compute granularity based on actual data span (not query range)
		minTime := traceAggs[0].TraceStartTime
		maxTime := traceAggs[0].TraceStartTime
		for _, agg := range traceAggs[1:] {
			if agg.TraceStartTime.Before(minTime) {
				minTime = agg.TraceStartTime
			}
			if agg.TraceStartTime.After(maxTime) {
				maxTime = agg.TraceStartTime
			}
		}
		dataSpan := maxTime.Sub(minTime)
		granularity = utils.CalculateAdaptiveGranularity(dataSpan, int64(len(traceAggs)))

		bucketAggs, err := s.repo.GetEvaluatorsTimeSeriesAggregated(monitorID, evaluatorNames, startTime, endTime, granularity)
		if err != nil {
			return nil, fmt.Errorf("failed to get batch time series aggregations: %w", err)
		}

		for _, agg := range bucketAggs {
			aggMap := make(map[string]interface{})
			if agg.MeanScore != nil {
				aggMap["mean"] = *agg.MeanScore
			} else {
				aggMap["mean"] = nil
			}
			evaluatorPoints[agg.EvaluatorName] = append(evaluatorPoints[agg.EvaluatorName], models.TimeSeriesPoint{
				Timestamp:    agg.TimeBucket,
				Count:        agg.TotalCount,
				SkippedCount: agg.SkippedCount,
				Aggregations: aggMap,
			})
		}
	}

	// Build ordered result preserving input evaluator order
	evaluators := make([]models.BatchTimeSeriesEvaluator, 0, len(evaluatorNames))
	for _, name := range evaluatorNames {
		pts := evaluatorPoints[name]
		if pts == nil {
			pts = []models.TimeSeriesPoint{}
		}
		evaluators = append(evaluators, models.BatchTimeSeriesEvaluator{
			EvaluatorName: name,
			Points:        pts,
		})
	}

	return &models.BatchTimeSeriesResponse{
		MonitorName: monitorName,
		Granularity: granularity,
		Evaluators:  evaluators,
	}, nil
}

// GetTraceScores returns all evaluation scores for a specific trace across all monitors.
// Scores are grouped by monitor, then split into trace-level evaluators and span-level groups.
func (s *MonitorScoresService) GetTraceScores(
	traceID, orgName, projName, agentName string,
) (*models.TraceScoresResponse, error) {
	scores, err := s.repo.GetScoresByTraceID(traceID, orgName, projName, agentName)
	if err != nil {
		return nil, fmt.Errorf("failed to get trace scores: %w", err)
	}

	// Group by monitor, then separate trace-level vs span-level scores
	type spanGroup struct {
		spanID     string
		spanLabel  string
		evaluators []models.TraceEvaluatorScore
	}

	type monitorGroup struct {
		monitorName string
		traceEvals  []models.TraceEvaluatorScore
		spans       map[string]*spanGroup
		spanOrder   []string
	}

	monitorMap := make(map[uuid.UUID]*monitorGroup)
	var monitorOrder []uuid.UUID

	for _, score := range scores {
		mg, exists := monitorMap[score.MonitorID]
		if !exists {
			mg = &monitorGroup{
				monitorName: score.MonitorName,
				spans:       make(map[string]*spanGroup),
			}
			monitorMap[score.MonitorID] = mg
			monitorOrder = append(monitorOrder, score.MonitorID)
		}

		evalScore := models.TraceEvaluatorScore{
			EvaluatorName: score.EvaluatorName,
			Score:         score.Score,
			Explanation:   score.Explanation,
			SkipReason:    score.SkipReason,
		}

		if score.SpanID == nil {
			// Trace-level score
			mg.traceEvals = append(mg.traceEvals, evalScore)
		} else {
			// Span-level score (agent or llm)
			sg, exists := mg.spans[*score.SpanID]
			if !exists {
				sg = &spanGroup{
					spanID:    *score.SpanID,
					spanLabel: score.SpanLabel,
				}
				mg.spans[*score.SpanID] = sg
				mg.spanOrder = append(mg.spanOrder, *score.SpanID)
			}
			sg.evaluators = append(sg.evaluators, evalScore)
		}
	}

	// Build response
	monitors := make([]models.TraceMonitorGroup, len(monitorOrder))
	for i, monitorID := range monitorOrder {
		mg := monitorMap[monitorID]

		spans := make([]models.TraceSpanGroup, len(mg.spanOrder))
		for j, spanID := range mg.spanOrder {
			sg := mg.spans[spanID]
			spans[j] = models.TraceSpanGroup{
				SpanID:     sg.spanID,
				SpanLabel:  sg.spanLabel,
				Evaluators: sg.evaluators,
			}
		}

		monitors[i] = models.TraceMonitorGroup{
			MonitorName: mg.monitorName,
			Evaluators:  mg.traceEvals,
			Spans:       spans,
		}
	}

	return &models.TraceScoresResponse{
		TraceID:  traceID,
		Monitors: monitors,
	}, nil
}

// GetAgentTraceScores returns aggregated scores per trace across all monitors for an agent.
func (s *MonitorScoresService) GetAgentTraceScores(
	orgName, projName, agentName string,
	startTime, endTime time.Time,
	limit, offset int,
) (*models.AgentTraceScoresResponse, error) {
	aggregations, totalCount, err := s.repo.GetAgentTraceScores(orgName, projName, agentName, startTime, endTime, limit, offset)
	if err != nil {
		return nil, fmt.Errorf("failed to get agent trace scores: %w", err)
	}

	traces := make([]models.TraceScoreSummary, len(aggregations))
	for i, agg := range aggregations {
		traces[i] = models.TraceScoreSummary{
			TraceID:      agg.TraceID,
			Score:        agg.MeanScore,
			TotalCount:   agg.TotalCount,
			SkippedCount: agg.SkippedCount,
		}
	}

	return &models.AgentTraceScoresResponse{
		Traces:     traces,
		TotalCount: totalCount,
	}, nil
}

// GetGroupedScores returns scores grouped by span label for agent/LLM breakdown tables.
func (s *MonitorScoresService) GetGroupedScores(
	monitorID uuid.UUID,
	monitorName string,
	startTime, endTime time.Time,
	level string,
) (*models.GroupedScoresResponse, error) {
	aggregations, err := s.repo.GetScoresGroupedByLabel(monitorID, startTime, endTime, level)
	if err != nil {
		return nil, fmt.Errorf("failed to get grouped scores: %w", err)
	}

	// Group flat aggregation rows by span_label
	groupMap := make(map[string][]models.LabelEvaluatorSummary)
	var groupOrder []string

	for _, agg := range aggregations {
		label := agg.SpanLabel
		if label == "" {
			label = "Unknown"
		}
		if _, exists := groupMap[label]; !exists {
			groupOrder = append(groupOrder, label)
		}

		groupMap[label] = append(groupMap[label], models.LabelEvaluatorSummary{
			EvaluatorName: agg.EvaluatorName,
			Mean:          agg.MeanScore,
			Count:         agg.TotalCount,
			SkippedCount:  agg.SkippedCount,
		})
	}

	groups := make([]models.ScoreLabelGroup, len(groupOrder))
	for i, label := range groupOrder {
		groups[i] = models.ScoreLabelGroup{
			Label:      label,
			Evaluators: groupMap[label],
		}
	}

	return &models.GroupedScoresResponse{
		MonitorName: monitorName,
		Level:       level,
		TimeRange: models.TimeRange{
			Start: startTime,
			End:   endTime,
		},
		Groups: groups,
	}, nil
}

// GetMonitorRunScores returns per-run aggregated scores from the MonitorRunEvaluator records.
func (s *MonitorScoresService) GetMonitorRunScores(
	monitorID uuid.UUID,
	runID uuid.UUID,
	monitorName string,
) (*models.MonitorRunScoresResponse, error) {
	// Validate that the monitor run exists before fetching evaluators
	_, err := s.monitorRepo.GetMonitorRunByID(runID, monitorID)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, utils.ErrMonitorRunNotFound
		}
		return nil, fmt.Errorf("failed to validate monitor run: %w", err)
	}

	evaluators, err := s.repo.GetEvaluatorsByMonitorAndRunID(monitorID, runID)
	if err != nil {
		return nil, fmt.Errorf("failed to get run evaluators: %w", err)
	}

	summaries := make([]models.EvaluatorScoreSummary, len(evaluators))
	for i, eval := range evaluators {
		aggs := eval.Aggregations
		if aggs == nil {
			aggs = make(map[string]interface{})
		}
		// When all evaluations were skipped, clear aggregations so the
		// frontend receives null/empty instead of a misleading 0.
		if eval.Count > 0 && eval.SkippedCount >= eval.Count {
			aggs = make(map[string]interface{})
		}
		summaries[i] = models.EvaluatorScoreSummary{
			EvaluatorName: eval.EvaluatorName,
			Level:         eval.Level,
			Count:         eval.Count,
			SkippedCount:  eval.SkippedCount,
			Aggregations:  aggs,
		}
	}

	return &models.MonitorRunScoresResponse{
		RunID:       runID.String(),
		MonitorName: monitorName,
		Evaluators:  summaries,
	}, nil
}

// GetMonitorID resolves monitor name to monitor ID
func (s *MonitorScoresService) GetMonitorID(orgName, projName, agentName, monitorName string) (uuid.UUID, error) {
	id, err := s.repo.GetMonitorID(orgName, projName, agentName, monitorName)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return uuid.Nil, fmt.Errorf("monitor %q not found: %w", monitorName, utils.ErrMonitorNotFound)
		}
		return uuid.Nil, fmt.Errorf("failed to query monitor: %w", err)
	}
	return id, nil
}
